<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDM_PENAHANAN', 'doctrine');

/**
 * BasePDM_PENAHANAN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tersangka
 * @property integer $jpu_idloktahan
 * @property timestamp $tgljpu_start
 * @property timestamp $tgljpu_end
 * @property integer $hakim_idloktahan
 * @property timestamp $tglhakim_start
 * @property timestamp $tglhakim_end
 * @property integer $ketuapn_idloktahan
 * @property timestamp $ketuapn_start
 * @property timestamp $ketuapn_end
 * @property integer $ketuapt_idloktahan
 * @property timestamp $ketuapt_start
 * @property timestamp $ketuapt_end
 * @property integer $pengalihan_idloktahan
 * @property timestamp $pengalihan_start
 * @property timestamp $pengalihan_end
 * @property integer $pembataran_idloktahan
 * @property timestamp $pembataran_start
 * @property timestamp $pembataran_end
 * @property integer $hakim1_idloktahan
 * @property timestamp $tglhakim1_start
 * @property timestamp $tglhakim1_end
 * @property integer $hakim2_idloktahan
 * @property timestamp $tglhakim2_start
 * @property timestamp $tglhakim2_end
 * @property integer $sidik_idloktahan
 * @property timestamp $sidik_start
 * @property timestamp $sidik_end
 * @property integer $sidikkejari_idloktahan
 * @property timestamp $sidikkejari_start
 * @property timestamp $sidikkejari_end
 * @property integer $sidikpn_idloktahan
 * @property timestamp $sidikpn_start
 * @property timestamp $sidikpn_end
 * 
 * @method integer       getId()                     Returns the current record's "id" value
 * @method integer       getIdTersangka()            Returns the current record's "id_tersangka" value
 * @method integer       getJpuIdloktahan()          Returns the current record's "jpu_idloktahan" value
 * @method timestamp     getTgljpuStart()            Returns the current record's "tgljpu_start" value
 * @method timestamp     getTgljpuEnd()              Returns the current record's "tgljpu_end" value
 * @method integer       getHakimIdloktahan()        Returns the current record's "hakim_idloktahan" value
 * @method timestamp     getTglhakimStart()          Returns the current record's "tglhakim_start" value
 * @method timestamp     getTglhakimEnd()            Returns the current record's "tglhakim_end" value
 * @method integer       getKetuapnIdloktahan()      Returns the current record's "ketuapn_idloktahan" value
 * @method timestamp     getKetuapnStart()           Returns the current record's "ketuapn_start" value
 * @method timestamp     getKetuapnEnd()             Returns the current record's "ketuapn_end" value
 * @method integer       getKetuaptIdloktahan()      Returns the current record's "ketuapt_idloktahan" value
 * @method timestamp     getKetuaptStart()           Returns the current record's "ketuapt_start" value
 * @method timestamp     getKetuaptEnd()             Returns the current record's "ketuapt_end" value
 * @method integer       getPengalihanIdloktahan()   Returns the current record's "pengalihan_idloktahan" value
 * @method timestamp     getPengalihanStart()        Returns the current record's "pengalihan_start" value
 * @method timestamp     getPengalihanEnd()          Returns the current record's "pengalihan_end" value
 * @method integer       getPembataranIdloktahan()   Returns the current record's "pembataran_idloktahan" value
 * @method timestamp     getPembataranStart()        Returns the current record's "pembataran_start" value
 * @method timestamp     getPembataranEnd()          Returns the current record's "pembataran_end" value
 * @method integer       getHakim1Idloktahan()       Returns the current record's "hakim1_idloktahan" value
 * @method timestamp     getTglhakim1Start()         Returns the current record's "tglhakim1_start" value
 * @method timestamp     getTglhakim1End()           Returns the current record's "tglhakim1_end" value
 * @method integer       getHakim2Idloktahan()       Returns the current record's "hakim2_idloktahan" value
 * @method timestamp     getTglhakim2Start()         Returns the current record's "tglhakim2_start" value
 * @method timestamp     getTglhakim2End()           Returns the current record's "tglhakim2_end" value
 * @method integer       getSidikIdloktahan()        Returns the current record's "sidik_idloktahan" value
 * @method timestamp     getSidikStart()             Returns the current record's "sidik_start" value
 * @method timestamp     getSidikEnd()               Returns the current record's "sidik_end" value
 * @method integer       getSidikkejariIdloktahan()  Returns the current record's "sidikkejari_idloktahan" value
 * @method timestamp     getSidikkejariStart()       Returns the current record's "sidikkejari_start" value
 * @method timestamp     getSidikkejariEnd()         Returns the current record's "sidikkejari_end" value
 * @method integer       getSidikpnIdloktahan()      Returns the current record's "sidikpn_idloktahan" value
 * @method timestamp     getSidikpnStart()           Returns the current record's "sidikpn_start" value
 * @method timestamp     getSidikpnEnd()             Returns the current record's "sidikpn_end" value
 * @method PDM_PENAHANAN setId()                     Sets the current record's "id" value
 * @method PDM_PENAHANAN setIdTersangka()            Sets the current record's "id_tersangka" value
 * @method PDM_PENAHANAN setJpuIdloktahan()          Sets the current record's "jpu_idloktahan" value
 * @method PDM_PENAHANAN setTgljpuStart()            Sets the current record's "tgljpu_start" value
 * @method PDM_PENAHANAN setTgljpuEnd()              Sets the current record's "tgljpu_end" value
 * @method PDM_PENAHANAN setHakimIdloktahan()        Sets the current record's "hakim_idloktahan" value
 * @method PDM_PENAHANAN setTglhakimStart()          Sets the current record's "tglhakim_start" value
 * @method PDM_PENAHANAN setTglhakimEnd()            Sets the current record's "tglhakim_end" value
 * @method PDM_PENAHANAN setKetuapnIdloktahan()      Sets the current record's "ketuapn_idloktahan" value
 * @method PDM_PENAHANAN setKetuapnStart()           Sets the current record's "ketuapn_start" value
 * @method PDM_PENAHANAN setKetuapnEnd()             Sets the current record's "ketuapn_end" value
 * @method PDM_PENAHANAN setKetuaptIdloktahan()      Sets the current record's "ketuapt_idloktahan" value
 * @method PDM_PENAHANAN setKetuaptStart()           Sets the current record's "ketuapt_start" value
 * @method PDM_PENAHANAN setKetuaptEnd()             Sets the current record's "ketuapt_end" value
 * @method PDM_PENAHANAN setPengalihanIdloktahan()   Sets the current record's "pengalihan_idloktahan" value
 * @method PDM_PENAHANAN setPengalihanStart()        Sets the current record's "pengalihan_start" value
 * @method PDM_PENAHANAN setPengalihanEnd()          Sets the current record's "pengalihan_end" value
 * @method PDM_PENAHANAN setPembataranIdloktahan()   Sets the current record's "pembataran_idloktahan" value
 * @method PDM_PENAHANAN setPembataranStart()        Sets the current record's "pembataran_start" value
 * @method PDM_PENAHANAN setPembataranEnd()          Sets the current record's "pembataran_end" value
 * @method PDM_PENAHANAN setHakim1Idloktahan()       Sets the current record's "hakim1_idloktahan" value
 * @method PDM_PENAHANAN setTglhakim1Start()         Sets the current record's "tglhakim1_start" value
 * @method PDM_PENAHANAN setTglhakim1End()           Sets the current record's "tglhakim1_end" value
 * @method PDM_PENAHANAN setHakim2Idloktahan()       Sets the current record's "hakim2_idloktahan" value
 * @method PDM_PENAHANAN setTglhakim2Start()         Sets the current record's "tglhakim2_start" value
 * @method PDM_PENAHANAN setTglhakim2End()           Sets the current record's "tglhakim2_end" value
 * @method PDM_PENAHANAN setSidikIdloktahan()        Sets the current record's "sidik_idloktahan" value
 * @method PDM_PENAHANAN setSidikStart()             Sets the current record's "sidik_start" value
 * @method PDM_PENAHANAN setSidikEnd()               Sets the current record's "sidik_end" value
 * @method PDM_PENAHANAN setSidikkejariIdloktahan()  Sets the current record's "sidikkejari_idloktahan" value
 * @method PDM_PENAHANAN setSidikkejariStart()       Sets the current record's "sidikkejari_start" value
 * @method PDM_PENAHANAN setSidikkejariEnd()         Sets the current record's "sidikkejari_end" value
 * @method PDM_PENAHANAN setSidikpnIdloktahan()      Sets the current record's "sidikpn_idloktahan" value
 * @method PDM_PENAHANAN setSidikpnStart()           Sets the current record's "sidikpn_start" value
 * @method PDM_PENAHANAN setSidikpnEnd()             Sets the current record's "sidikpn_end" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDM_PENAHANAN extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDM_PENAHANAN');
        $this->hasColumn('id', 'integer', 8, array(
             'notnull' => true,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jpu_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tgljpu_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgljpu_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('hakim_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tglhakim_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tglhakim_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapn_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ketuapn_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapn_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapt_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ketuapt_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapt_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pengalihan_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('pengalihan_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pengalihan_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pembataran_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('pembataran_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pembataran_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('hakim1_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tglhakim1_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tglhakim1_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('hakim2_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tglhakim2_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tglhakim2_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidik_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('sidik_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidik_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidikkejari_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('sidikkejari_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidikkejari_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidikpn_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('sidikpn_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('sidikpn_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}