<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/26 11:03:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'oracle://simkari:bandung@10.1.4.53/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.4.53)(PORT=1521)))(CONNECT_DATA=(SID=SIMKARI)))',
  'name' => 'doctrine',
)),);
