<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/14 08:29:44
sfConfig::add(array(
  'mod_barangrampasan_enabled' => true,
  'mod_barangrampasan_view_class' => 'sfPHP',
));
