<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/09 20:03:30
sfConfig::add(array(
  'mod_barangrampasan_enabled' => true,
  'mod_barangrampasan_view_class' => 'sfPHP',
));
