<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/26 11:36:36
sfConfig::add(array(
  'mod_barangrampasan_enabled' => true,
  'mod_barangrampasan_view_class' => 'sfPHP',
));
