<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_SITA', 'doctrine');

/**
 * BasePDS_SITA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_perkara
 * @property string $sp_sita_no
 * @property timestamp $sp_sita_tgl
 * @property string $izin_no
 * @property timestamp $izin_tgl
 * @property PDS_PERKARA $PDS_PERKARA
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getIdPerkara()   Returns the current record's "id_perkara" value
 * @method string      getSpSitaNo()    Returns the current record's "sp_sita_no" value
 * @method timestamp   getSpSitaTgl()   Returns the current record's "sp_sita_tgl" value
 * @method string      getIzinNo()      Returns the current record's "izin_no" value
 * @method timestamp   getIzinTgl()     Returns the current record's "izin_tgl" value
 * @method PDS_PERKARA getPDSPERKARA()  Returns the current record's "PDS_PERKARA" value
 * @method PDS_SITA    setId()          Sets the current record's "id" value
 * @method PDS_SITA    setIdPerkara()   Sets the current record's "id_perkara" value
 * @method PDS_SITA    setSpSitaNo()    Sets the current record's "sp_sita_no" value
 * @method PDS_SITA    setSpSitaTgl()   Sets the current record's "sp_sita_tgl" value
 * @method PDS_SITA    setIzinNo()      Sets the current record's "izin_no" value
 * @method PDS_SITA    setIzinTgl()     Sets the current record's "izin_tgl" value
 * @method PDS_SITA    setPDSPERKARA()  Sets the current record's "PDS_PERKARA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_SITA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_SITA');
        $this->hasColumn('id', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('sp_sita_no', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('sp_sita_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('izin_no', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('izin_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_PERKARA', array(
             'local' => 'id_perkara',
             'foreign' => 'id'));
    }
}