<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_BERKAS', 'doctrine');

/**
 * BasePDS_BERKAS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_perkara
 * @property integer $nomor
 * @property timestamp $tgl_diterima
 * @property string $no_p18
 * @property timestamp $tgl_p18
 * @property string $no_p19
 * @property timestamp $tgl_p19
 * @property string $isi_petunjuk
 * @property string $st_insert
 * @property string $nama_berkas_petunjuk
 * @property PDS_PERKARA $PDS_PERKARA
 * 
 * @method integer     getId()                   Returns the current record's "id" value
 * @method integer     getIdPerkara()            Returns the current record's "id_perkara" value
 * @method integer     getNomor()                Returns the current record's "nomor" value
 * @method timestamp   getTglDiterima()          Returns the current record's "tgl_diterima" value
 * @method string      getNoP18()                Returns the current record's "no_p18" value
 * @method timestamp   getTglP18()               Returns the current record's "tgl_p18" value
 * @method string      getNoP19()                Returns the current record's "no_p19" value
 * @method timestamp   getTglP19()               Returns the current record's "tgl_p19" value
 * @method string      getIsiPetunjuk()          Returns the current record's "isi_petunjuk" value
 * @method string      getStInsert()             Returns the current record's "st_insert" value
 * @method string      getNamaBerkasPetunjuk()   Returns the current record's "nama_berkas_petunjuk" value
 * @method PDS_PERKARA getPDSPERKARA()           Returns the current record's "PDS_PERKARA" value
 * @method PDS_BERKAS  setId()                   Sets the current record's "id" value
 * @method PDS_BERKAS  setIdPerkara()            Sets the current record's "id_perkara" value
 * @method PDS_BERKAS  setNomor()                Sets the current record's "nomor" value
 * @method PDS_BERKAS  setTglDiterima()          Sets the current record's "tgl_diterima" value
 * @method PDS_BERKAS  setNoP18()                Sets the current record's "no_p18" value
 * @method PDS_BERKAS  setTglP18()               Sets the current record's "tgl_p18" value
 * @method PDS_BERKAS  setNoP19()                Sets the current record's "no_p19" value
 * @method PDS_BERKAS  setTglP19()               Sets the current record's "tgl_p19" value
 * @method PDS_BERKAS  setIsiPetunjuk()          Sets the current record's "isi_petunjuk" value
 * @method PDS_BERKAS  setStInsert()             Sets the current record's "st_insert" value
 * @method PDS_BERKAS  setNamaBerkasPetunjuk()   Sets the current record's "nama_berkas_petunjuk" value
 * @method PDS_BERKAS  setPDSPERKARA()           Sets the current record's "PDS_PERKARA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_BERKAS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_BERKAS');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nomor', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('tgl_diterima', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_p18', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_p18', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_p19', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_p19', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_petunjuk', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('st_insert', 'string', 1, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('nama_berkas_petunjuk', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_PERKARA', array(
             'local' => 'id_perkara',
             'foreign' => 'id'));
    }
}