<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_PENAHANAN', 'doctrine');

/**
 * BasePDS_PENAHANAN
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tersangka
 * @property integer $hakim_idloktahan
 * @property timestamp $tglhakim_start
 * @property timestamp $tglhakim_end
 * @property integer $ketuapn_idloktahan
 * @property timestamp $ketuapn_start
 * @property timestamp $ketuapn_end
 * @property integer $ketuapt_idloktahan
 * @property timestamp $ketuapt_start
 * @property timestamp $ketuapt_end
 * @property string $created_by
 * @property string $created_ip
 * @property timestamp $created_time
 * @property string $lastupdate_by
 * @property string $lastupdate_ip
 * @property timestamp $lastupdate_time
 * @property PDS_TERSANGKA $PDS_TERSANGKA
 * 
 * @method integer       getId()                 Returns the current record's "id" value
 * @method integer       getIdTersangka()        Returns the current record's "id_tersangka" value
 * @method integer       getHakimIdloktahan()    Returns the current record's "hakim_idloktahan" value
 * @method timestamp     getTglhakimStart()      Returns the current record's "tglhakim_start" value
 * @method timestamp     getTglhakimEnd()        Returns the current record's "tglhakim_end" value
 * @method integer       getKetuapnIdloktahan()  Returns the current record's "ketuapn_idloktahan" value
 * @method timestamp     getKetuapnStart()       Returns the current record's "ketuapn_start" value
 * @method timestamp     getKetuapnEnd()         Returns the current record's "ketuapn_end" value
 * @method integer       getKetuaptIdloktahan()  Returns the current record's "ketuapt_idloktahan" value
 * @method timestamp     getKetuaptStart()       Returns the current record's "ketuapt_start" value
 * @method timestamp     getKetuaptEnd()         Returns the current record's "ketuapt_end" value
 * @method string        getCreatedBy()          Returns the current record's "created_by" value
 * @method string        getCreatedIp()          Returns the current record's "created_ip" value
 * @method timestamp     getCreatedTime()        Returns the current record's "created_time" value
 * @method string        getLastupdateBy()       Returns the current record's "lastupdate_by" value
 * @method string        getLastupdateIp()       Returns the current record's "lastupdate_ip" value
 * @method timestamp     getLastupdateTime()     Returns the current record's "lastupdate_time" value
 * @method PDS_TERSANGKA getPDSTERSANGKA()       Returns the current record's "PDS_TERSANGKA" value
 * @method PDS_PENAHANAN setId()                 Sets the current record's "id" value
 * @method PDS_PENAHANAN setIdTersangka()        Sets the current record's "id_tersangka" value
 * @method PDS_PENAHANAN setHakimIdloktahan()    Sets the current record's "hakim_idloktahan" value
 * @method PDS_PENAHANAN setTglhakimStart()      Sets the current record's "tglhakim_start" value
 * @method PDS_PENAHANAN setTglhakimEnd()        Sets the current record's "tglhakim_end" value
 * @method PDS_PENAHANAN setKetuapnIdloktahan()  Sets the current record's "ketuapn_idloktahan" value
 * @method PDS_PENAHANAN setKetuapnStart()       Sets the current record's "ketuapn_start" value
 * @method PDS_PENAHANAN setKetuapnEnd()         Sets the current record's "ketuapn_end" value
 * @method PDS_PENAHANAN setKetuaptIdloktahan()  Sets the current record's "ketuapt_idloktahan" value
 * @method PDS_PENAHANAN setKetuaptStart()       Sets the current record's "ketuapt_start" value
 * @method PDS_PENAHANAN setKetuaptEnd()         Sets the current record's "ketuapt_end" value
 * @method PDS_PENAHANAN setCreatedBy()          Sets the current record's "created_by" value
 * @method PDS_PENAHANAN setCreatedIp()          Sets the current record's "created_ip" value
 * @method PDS_PENAHANAN setCreatedTime()        Sets the current record's "created_time" value
 * @method PDS_PENAHANAN setLastupdateBy()       Sets the current record's "lastupdate_by" value
 * @method PDS_PENAHANAN setLastupdateIp()       Sets the current record's "lastupdate_ip" value
 * @method PDS_PENAHANAN setLastupdateTime()     Sets the current record's "lastupdate_time" value
 * @method PDS_PENAHANAN setPDSTERSANGKA()       Sets the current record's "PDS_TERSANGKA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_PENAHANAN extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_PENAHANAN');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('hakim_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tglhakim_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tglhakim_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapn_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ketuapn_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapn_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapt_idloktahan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ketuapt_start', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ketuapt_end', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('created_by', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('created_ip', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('created_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lastupdate_by', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('lastupdate_ip', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('lastupdate_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_TERSANGKA', array(
             'local' => 'id_tersangka',
             'foreign' => 'id'));
    }
}