<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_BERKAS_FILE', 'doctrine');

/**
 * BasePDS_BERKAS_FILE
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_perkara
 * @property string $file_type
 * @property string $file_name
 * @property float $file_size
 * @property timestamp $upload_date
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getIdPerkara()   Returns the current record's "id_perkara" value
 * @method string          getFileType()    Returns the current record's "file_type" value
 * @method string          getFileName()    Returns the current record's "file_name" value
 * @method float           getFileSize()    Returns the current record's "file_size" value
 * @method timestamp       getUploadDate()  Returns the current record's "upload_date" value
 * @method PDS_BERKAS_FILE setId()          Sets the current record's "id" value
 * @method PDS_BERKAS_FILE setIdPerkara()   Sets the current record's "id_perkara" value
 * @method PDS_BERKAS_FILE setFileType()    Sets the current record's "file_type" value
 * @method PDS_BERKAS_FILE setFileName()    Sets the current record's "file_name" value
 * @method PDS_BERKAS_FILE setFileSize()    Sets the current record's "file_size" value
 * @method PDS_BERKAS_FILE setUploadDate()  Sets the current record's "upload_date" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_BERKAS_FILE extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_BERKAS_FILE');
        $this->hasColumn('id', 'integer', 8, array(
             'notnull' => true,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('file_type', 'string', 4, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 150, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 150,
             ));
        $this->hasColumn('file_size', 'float', 22, array(
             'notnull' => false,
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 22,
             ));
        $this->hasColumn('upload_date', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'default' => 'SYSDATE
                ',
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}