<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_EKS_MATI', 'doctrine');

/**
 * BasePDS_EKS_MATI
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tersangka
 * @property string $pelaksanaan
 * @property string $berkas
 * @property string $no_surat_hambatan
 * @property timestamp $tgl_surat_hambatan
 * @property string $ringkasan_hambatan
 * @property string $no_surat_petunjuk
 * @property timestamp $tgl_surat_petunjuk
 * @property string $ringkasan_petunjuk
 * @property string $created_by
 * @property string $created_ip
 * @property timestamp $created_time
 * @property string $lastupdate_by
 * @property string $lastupdate_ip
 * @property timestamp $lastupdate_time
 * 
 * @method integer      getId()                 Returns the current record's "id" value
 * @method integer      getIdTersangka()        Returns the current record's "id_tersangka" value
 * @method string       getPelaksanaan()        Returns the current record's "pelaksanaan" value
 * @method string       getBerkas()             Returns the current record's "berkas" value
 * @method string       getNoSuratHambatan()    Returns the current record's "no_surat_hambatan" value
 * @method timestamp    getTglSuratHambatan()   Returns the current record's "tgl_surat_hambatan" value
 * @method string       getRingkasanHambatan()  Returns the current record's "ringkasan_hambatan" value
 * @method string       getNoSuratPetunjuk()    Returns the current record's "no_surat_petunjuk" value
 * @method timestamp    getTglSuratPetunjuk()   Returns the current record's "tgl_surat_petunjuk" value
 * @method string       getRingkasanPetunjuk()  Returns the current record's "ringkasan_petunjuk" value
 * @method string       getCreatedBy()          Returns the current record's "created_by" value
 * @method string       getCreatedIp()          Returns the current record's "created_ip" value
 * @method timestamp    getCreatedTime()        Returns the current record's "created_time" value
 * @method string       getLastupdateBy()       Returns the current record's "lastupdate_by" value
 * @method string       getLastupdateIp()       Returns the current record's "lastupdate_ip" value
 * @method timestamp    getLastupdateTime()     Returns the current record's "lastupdate_time" value
 * @method PDS_EKS_MATI setId()                 Sets the current record's "id" value
 * @method PDS_EKS_MATI setIdTersangka()        Sets the current record's "id_tersangka" value
 * @method PDS_EKS_MATI setPelaksanaan()        Sets the current record's "pelaksanaan" value
 * @method PDS_EKS_MATI setBerkas()             Sets the current record's "berkas" value
 * @method PDS_EKS_MATI setNoSuratHambatan()    Sets the current record's "no_surat_hambatan" value
 * @method PDS_EKS_MATI setTglSuratHambatan()   Sets the current record's "tgl_surat_hambatan" value
 * @method PDS_EKS_MATI setRingkasanHambatan()  Sets the current record's "ringkasan_hambatan" value
 * @method PDS_EKS_MATI setNoSuratPetunjuk()    Sets the current record's "no_surat_petunjuk" value
 * @method PDS_EKS_MATI setTglSuratPetunjuk()   Sets the current record's "tgl_surat_petunjuk" value
 * @method PDS_EKS_MATI setRingkasanPetunjuk()  Sets the current record's "ringkasan_petunjuk" value
 * @method PDS_EKS_MATI setCreatedBy()          Sets the current record's "created_by" value
 * @method PDS_EKS_MATI setCreatedIp()          Sets the current record's "created_ip" value
 * @method PDS_EKS_MATI setCreatedTime()        Sets the current record's "created_time" value
 * @method PDS_EKS_MATI setLastupdateBy()       Sets the current record's "lastupdate_by" value
 * @method PDS_EKS_MATI setLastupdateIp()       Sets the current record's "lastupdate_ip" value
 * @method PDS_EKS_MATI setLastupdateTime()     Sets the current record's "lastupdate_time" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_EKS_MATI extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_EKS_MATI');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('pelaksanaan', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('berkas', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('no_surat_hambatan', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_surat_hambatan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ringkasan_hambatan', 'string', 300, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 300,
             ));
        $this->hasColumn('no_surat_petunjuk', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('tgl_surat_petunjuk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ringkasan_petunjuk', 'string', 300, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 300,
             ));
        $this->hasColumn('created_by', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('created_ip', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('created_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lastupdate_by', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('lastupdate_ip', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('lastupdate_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}