<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_RENTUT', 'doctrine');

/**
 * BasePDS_RENTUT
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tersangka
 * @property integer $r1_pj_pidana_coba_thn
 * @property integer $r1_pj_pidana_coba_bln
 * @property integer $r1_pj_pidana_coba_hari
 * @property integer $r1_pj_badan_tahun
 * @property integer $r1_pj_badan_bulan
 * @property integer $r1_pj_badan_hari
 * @property decimal $r1_pj_denda_rp
 * @property integer $r1_pj_sub_tahun
 * @property integer $r1_pj_sub_bulan
 * @property integer $r1_pj_sub_hari
 * @property decimal $r1_pj_biaya
 * @property integer $r1_kurungan_tahun
 * @property integer $r1_kurungan_bulan
 * @property integer $r1_kurungan_hari
 * @property decimal $r1_denda
 * @property string $r1_putusan_tambahan
 * @property integer $r2_pj_pidana_coba_thn
 * @property integer $r2_pj_pidana_coba_bln
 * @property integer $r2_pj_pidana_coba_hari
 * @property integer $r2_pj_badan_tahun
 * @property integer $r2_pj_badan_bulan
 * @property integer $r2_pj_badan_hari
 * @property decimal $r2_pj_denda_rp
 * @property integer $r2_pj_sub_tahun
 * @property integer $r2_pj_sub_bulan
 * @property integer $r2_pj_sub_hari
 * @property decimal $r2_pj_biaya
 * @property integer $r2_kurungan_tahun
 * @property integer $r2_kurungan_bulan
 * @property integer $r2_kurungan_hari
 * @property decimal $r2_denda
 * @property string $r2_putusan_tambahan
 * @property integer $r3_pj_pidana_coba_thn
 * @property integer $r3_pj_pidana_coba_bln
 * @property integer $r3_pj_pidana_coba_hari
 * @property integer $r3_pj_badan_tahun
 * @property integer $r3_pj_badan_bulan
 * @property integer $r3_pj_badan_hari
 * @property decimal $r3_pj_denda_rp
 * @property integer $r3_pj_sub_tahun
 * @property integer $r3_pj_sub_bulan
 * @property integer $r3_pj_sub_hari
 * @property decimal $r3_pj_biaya
 * @property integer $r3_kurungan_tahun
 * @property integer $r3_kurungan_bulan
 * @property integer $r3_kurungan_hari
 * @property decimal $r3_denda
 * @property string $r3_putusan_tambahan
 * @property integer $r4_pj_pidana_coba_thn
 * @property integer $r4_pj_pidana_coba_bln
 * @property integer $r4_pj_pidana_coba_hari
 * @property integer $r4_pj_badan_tahun
 * @property integer $r4_pj_badan_bulan
 * @property integer $r4_pj_badan_hari
 * @property decimal $r4_pj_denda_rp
 * @property integer $r4_pj_sub_tahun
 * @property integer $r4_pj_sub_bulan
 * @property integer $r4_pj_sub_hari
 * @property decimal $r4_pj_biaya
 * @property integer $r4_kurungan_tahun
 * @property integer $r4_kurungan_bulan
 * @property integer $r4_kurungan_hari
 * @property decimal $r4_denda
 * @property string $r4_putusan_tambahan
 * @property integer $r5_pj_pidana_coba_thn
 * @property integer $r5_pj_pidana_coba_bln
 * @property integer $r5_pj_pidana_coba_hari
 * @property integer $r5_pj_badan_tahun
 * @property integer $r5_pj_badan_bulan
 * @property integer $r5_pj_badan_hari
 * @property decimal $r5_pj_denda_rp
 * @property integer $r5_pj_sub_tahun
 * @property integer $r5_pj_sub_bulan
 * @property integer $r5_pj_sub_hari
 * @property decimal $r5_pj_biaya
 * @property integer $r5_kurungan_tahun
 * @property integer $r5_kurungan_bulan
 * @property integer $r5_kurungan_hari
 * @property decimal $r5_denda
 * @property string $r5_putusan_tambahan
 * @property integer $r1_pdn_pengawasan
 * @property integer $r2_pdn_pengawasan
 * @property integer $r3_pdn_pengawasan
 * @property integer $r4_pdn_pengawasan
 * @property integer $r5_pdn_pengawasan
 * @property integer $r1_jns_bebas
 * @property integer $r2_jns_bebas
 * @property integer $r3_jns_bebas
 * @property integer $r4_jns_bebas
 * @property integer $r5_jns_bebas
 * @property PDS_TERSANGKA $PDS_TERSANGKA
 * 
 * @method integer       getId()                     Returns the current record's "id" value
 * @method integer       getIdTersangka()            Returns the current record's "id_tersangka" value
 * @method integer       getR1PjPidanaCobaThn()      Returns the current record's "r1_pj_pidana_coba_thn" value
 * @method integer       getR1PjPidanaCobaBln()      Returns the current record's "r1_pj_pidana_coba_bln" value
 * @method integer       getR1PjPidanaCobaHari()     Returns the current record's "r1_pj_pidana_coba_hari" value
 * @method integer       getR1PjBadanTahun()         Returns the current record's "r1_pj_badan_tahun" value
 * @method integer       getR1PjBadanBulan()         Returns the current record's "r1_pj_badan_bulan" value
 * @method integer       getR1PjBadanHari()          Returns the current record's "r1_pj_badan_hari" value
 * @method decimal       getR1PjDendaRp()            Returns the current record's "r1_pj_denda_rp" value
 * @method integer       getR1PjSubTahun()           Returns the current record's "r1_pj_sub_tahun" value
 * @method integer       getR1PjSubBulan()           Returns the current record's "r1_pj_sub_bulan" value
 * @method integer       getR1PjSubHari()            Returns the current record's "r1_pj_sub_hari" value
 * @method decimal       getR1PjBiaya()              Returns the current record's "r1_pj_biaya" value
 * @method integer       getR1KurunganTahun()        Returns the current record's "r1_kurungan_tahun" value
 * @method integer       getR1KurunganBulan()        Returns the current record's "r1_kurungan_bulan" value
 * @method integer       getR1KurunganHari()         Returns the current record's "r1_kurungan_hari" value
 * @method decimal       getR1Denda()                Returns the current record's "r1_denda" value
 * @method string        getR1PutusanTambahan()      Returns the current record's "r1_putusan_tambahan" value
 * @method integer       getR2PjPidanaCobaThn()      Returns the current record's "r2_pj_pidana_coba_thn" value
 * @method integer       getR2PjPidanaCobaBln()      Returns the current record's "r2_pj_pidana_coba_bln" value
 * @method integer       getR2PjPidanaCobaHari()     Returns the current record's "r2_pj_pidana_coba_hari" value
 * @method integer       getR2PjBadanTahun()         Returns the current record's "r2_pj_badan_tahun" value
 * @method integer       getR2PjBadanBulan()         Returns the current record's "r2_pj_badan_bulan" value
 * @method integer       getR2PjBadanHari()          Returns the current record's "r2_pj_badan_hari" value
 * @method decimal       getR2PjDendaRp()            Returns the current record's "r2_pj_denda_rp" value
 * @method integer       getR2PjSubTahun()           Returns the current record's "r2_pj_sub_tahun" value
 * @method integer       getR2PjSubBulan()           Returns the current record's "r2_pj_sub_bulan" value
 * @method integer       getR2PjSubHari()            Returns the current record's "r2_pj_sub_hari" value
 * @method decimal       getR2PjBiaya()              Returns the current record's "r2_pj_biaya" value
 * @method integer       getR2KurunganTahun()        Returns the current record's "r2_kurungan_tahun" value
 * @method integer       getR2KurunganBulan()        Returns the current record's "r2_kurungan_bulan" value
 * @method integer       getR2KurunganHari()         Returns the current record's "r2_kurungan_hari" value
 * @method decimal       getR2Denda()                Returns the current record's "r2_denda" value
 * @method string        getR2PutusanTambahan()      Returns the current record's "r2_putusan_tambahan" value
 * @method integer       getR3PjPidanaCobaThn()      Returns the current record's "r3_pj_pidana_coba_thn" value
 * @method integer       getR3PjPidanaCobaBln()      Returns the current record's "r3_pj_pidana_coba_bln" value
 * @method integer       getR3PjPidanaCobaHari()     Returns the current record's "r3_pj_pidana_coba_hari" value
 * @method integer       getR3PjBadanTahun()         Returns the current record's "r3_pj_badan_tahun" value
 * @method integer       getR3PjBadanBulan()         Returns the current record's "r3_pj_badan_bulan" value
 * @method integer       getR3PjBadanHari()          Returns the current record's "r3_pj_badan_hari" value
 * @method decimal       getR3PjDendaRp()            Returns the current record's "r3_pj_denda_rp" value
 * @method integer       getR3PjSubTahun()           Returns the current record's "r3_pj_sub_tahun" value
 * @method integer       getR3PjSubBulan()           Returns the current record's "r3_pj_sub_bulan" value
 * @method integer       getR3PjSubHari()            Returns the current record's "r3_pj_sub_hari" value
 * @method decimal       getR3PjBiaya()              Returns the current record's "r3_pj_biaya" value
 * @method integer       getR3KurunganTahun()        Returns the current record's "r3_kurungan_tahun" value
 * @method integer       getR3KurunganBulan()        Returns the current record's "r3_kurungan_bulan" value
 * @method integer       getR3KurunganHari()         Returns the current record's "r3_kurungan_hari" value
 * @method decimal       getR3Denda()                Returns the current record's "r3_denda" value
 * @method string        getR3PutusanTambahan()      Returns the current record's "r3_putusan_tambahan" value
 * @method integer       getR4PjPidanaCobaThn()      Returns the current record's "r4_pj_pidana_coba_thn" value
 * @method integer       getR4PjPidanaCobaBln()      Returns the current record's "r4_pj_pidana_coba_bln" value
 * @method integer       getR4PjPidanaCobaHari()     Returns the current record's "r4_pj_pidana_coba_hari" value
 * @method integer       getR4PjBadanTahun()         Returns the current record's "r4_pj_badan_tahun" value
 * @method integer       getR4PjBadanBulan()         Returns the current record's "r4_pj_badan_bulan" value
 * @method integer       getR4PjBadanHari()          Returns the current record's "r4_pj_badan_hari" value
 * @method decimal       getR4PjDendaRp()            Returns the current record's "r4_pj_denda_rp" value
 * @method integer       getR4PjSubTahun()           Returns the current record's "r4_pj_sub_tahun" value
 * @method integer       getR4PjSubBulan()           Returns the current record's "r4_pj_sub_bulan" value
 * @method integer       getR4PjSubHari()            Returns the current record's "r4_pj_sub_hari" value
 * @method decimal       getR4PjBiaya()              Returns the current record's "r4_pj_biaya" value
 * @method integer       getR4KurunganTahun()        Returns the current record's "r4_kurungan_tahun" value
 * @method integer       getR4KurunganBulan()        Returns the current record's "r4_kurungan_bulan" value
 * @method integer       getR4KurunganHari()         Returns the current record's "r4_kurungan_hari" value
 * @method decimal       getR4Denda()                Returns the current record's "r4_denda" value
 * @method string        getR4PutusanTambahan()      Returns the current record's "r4_putusan_tambahan" value
 * @method integer       getR5PjPidanaCobaThn()      Returns the current record's "r5_pj_pidana_coba_thn" value
 * @method integer       getR5PjPidanaCobaBln()      Returns the current record's "r5_pj_pidana_coba_bln" value
 * @method integer       getR5PjPidanaCobaHari()     Returns the current record's "r5_pj_pidana_coba_hari" value
 * @method integer       getR5PjBadanTahun()         Returns the current record's "r5_pj_badan_tahun" value
 * @method integer       getR5PjBadanBulan()         Returns the current record's "r5_pj_badan_bulan" value
 * @method integer       getR5PjBadanHari()          Returns the current record's "r5_pj_badan_hari" value
 * @method decimal       getR5PjDendaRp()            Returns the current record's "r5_pj_denda_rp" value
 * @method integer       getR5PjSubTahun()           Returns the current record's "r5_pj_sub_tahun" value
 * @method integer       getR5PjSubBulan()           Returns the current record's "r5_pj_sub_bulan" value
 * @method integer       getR5PjSubHari()            Returns the current record's "r5_pj_sub_hari" value
 * @method decimal       getR5PjBiaya()              Returns the current record's "r5_pj_biaya" value
 * @method integer       getR5KurunganTahun()        Returns the current record's "r5_kurungan_tahun" value
 * @method integer       getR5KurunganBulan()        Returns the current record's "r5_kurungan_bulan" value
 * @method integer       getR5KurunganHari()         Returns the current record's "r5_kurungan_hari" value
 * @method decimal       getR5Denda()                Returns the current record's "r5_denda" value
 * @method string        getR5PutusanTambahan()      Returns the current record's "r5_putusan_tambahan" value
 * @method integer       getR1PdnPengawasan()        Returns the current record's "r1_pdn_pengawasan" value
 * @method integer       getR2PdnPengawasan()        Returns the current record's "r2_pdn_pengawasan" value
 * @method integer       getR3PdnPengawasan()        Returns the current record's "r3_pdn_pengawasan" value
 * @method integer       getR4PdnPengawasan()        Returns the current record's "r4_pdn_pengawasan" value
 * @method integer       getR5PdnPengawasan()        Returns the current record's "r5_pdn_pengawasan" value
 * @method integer       getR1JnsBebas()             Returns the current record's "r1_jns_bebas" value
 * @method integer       getR2JnsBebas()             Returns the current record's "r2_jns_bebas" value
 * @method integer       getR3JnsBebas()             Returns the current record's "r3_jns_bebas" value
 * @method integer       getR4JnsBebas()             Returns the current record's "r4_jns_bebas" value
 * @method integer       getR5JnsBebas()             Returns the current record's "r5_jns_bebas" value
 * @method PDS_TERSANGKA getPDSTERSANGKA()           Returns the current record's "PDS_TERSANGKA" value
 * @method PDS_RENTUT    setId()                     Sets the current record's "id" value
 * @method PDS_RENTUT    setIdTersangka()            Sets the current record's "id_tersangka" value
 * @method PDS_RENTUT    setR1PjPidanaCobaThn()      Sets the current record's "r1_pj_pidana_coba_thn" value
 * @method PDS_RENTUT    setR1PjPidanaCobaBln()      Sets the current record's "r1_pj_pidana_coba_bln" value
 * @method PDS_RENTUT    setR1PjPidanaCobaHari()     Sets the current record's "r1_pj_pidana_coba_hari" value
 * @method PDS_RENTUT    setR1PjBadanTahun()         Sets the current record's "r1_pj_badan_tahun" value
 * @method PDS_RENTUT    setR1PjBadanBulan()         Sets the current record's "r1_pj_badan_bulan" value
 * @method PDS_RENTUT    setR1PjBadanHari()          Sets the current record's "r1_pj_badan_hari" value
 * @method PDS_RENTUT    setR1PjDendaRp()            Sets the current record's "r1_pj_denda_rp" value
 * @method PDS_RENTUT    setR1PjSubTahun()           Sets the current record's "r1_pj_sub_tahun" value
 * @method PDS_RENTUT    setR1PjSubBulan()           Sets the current record's "r1_pj_sub_bulan" value
 * @method PDS_RENTUT    setR1PjSubHari()            Sets the current record's "r1_pj_sub_hari" value
 * @method PDS_RENTUT    setR1PjBiaya()              Sets the current record's "r1_pj_biaya" value
 * @method PDS_RENTUT    setR1KurunganTahun()        Sets the current record's "r1_kurungan_tahun" value
 * @method PDS_RENTUT    setR1KurunganBulan()        Sets the current record's "r1_kurungan_bulan" value
 * @method PDS_RENTUT    setR1KurunganHari()         Sets the current record's "r1_kurungan_hari" value
 * @method PDS_RENTUT    setR1Denda()                Sets the current record's "r1_denda" value
 * @method PDS_RENTUT    setR1PutusanTambahan()      Sets the current record's "r1_putusan_tambahan" value
 * @method PDS_RENTUT    setR2PjPidanaCobaThn()      Sets the current record's "r2_pj_pidana_coba_thn" value
 * @method PDS_RENTUT    setR2PjPidanaCobaBln()      Sets the current record's "r2_pj_pidana_coba_bln" value
 * @method PDS_RENTUT    setR2PjPidanaCobaHari()     Sets the current record's "r2_pj_pidana_coba_hari" value
 * @method PDS_RENTUT    setR2PjBadanTahun()         Sets the current record's "r2_pj_badan_tahun" value
 * @method PDS_RENTUT    setR2PjBadanBulan()         Sets the current record's "r2_pj_badan_bulan" value
 * @method PDS_RENTUT    setR2PjBadanHari()          Sets the current record's "r2_pj_badan_hari" value
 * @method PDS_RENTUT    setR2PjDendaRp()            Sets the current record's "r2_pj_denda_rp" value
 * @method PDS_RENTUT    setR2PjSubTahun()           Sets the current record's "r2_pj_sub_tahun" value
 * @method PDS_RENTUT    setR2PjSubBulan()           Sets the current record's "r2_pj_sub_bulan" value
 * @method PDS_RENTUT    setR2PjSubHari()            Sets the current record's "r2_pj_sub_hari" value
 * @method PDS_RENTUT    setR2PjBiaya()              Sets the current record's "r2_pj_biaya" value
 * @method PDS_RENTUT    setR2KurunganTahun()        Sets the current record's "r2_kurungan_tahun" value
 * @method PDS_RENTUT    setR2KurunganBulan()        Sets the current record's "r2_kurungan_bulan" value
 * @method PDS_RENTUT    setR2KurunganHari()         Sets the current record's "r2_kurungan_hari" value
 * @method PDS_RENTUT    setR2Denda()                Sets the current record's "r2_denda" value
 * @method PDS_RENTUT    setR2PutusanTambahan()      Sets the current record's "r2_putusan_tambahan" value
 * @method PDS_RENTUT    setR3PjPidanaCobaThn()      Sets the current record's "r3_pj_pidana_coba_thn" value
 * @method PDS_RENTUT    setR3PjPidanaCobaBln()      Sets the current record's "r3_pj_pidana_coba_bln" value
 * @method PDS_RENTUT    setR3PjPidanaCobaHari()     Sets the current record's "r3_pj_pidana_coba_hari" value
 * @method PDS_RENTUT    setR3PjBadanTahun()         Sets the current record's "r3_pj_badan_tahun" value
 * @method PDS_RENTUT    setR3PjBadanBulan()         Sets the current record's "r3_pj_badan_bulan" value
 * @method PDS_RENTUT    setR3PjBadanHari()          Sets the current record's "r3_pj_badan_hari" value
 * @method PDS_RENTUT    setR3PjDendaRp()            Sets the current record's "r3_pj_denda_rp" value
 * @method PDS_RENTUT    setR3PjSubTahun()           Sets the current record's "r3_pj_sub_tahun" value
 * @method PDS_RENTUT    setR3PjSubBulan()           Sets the current record's "r3_pj_sub_bulan" value
 * @method PDS_RENTUT    setR3PjSubHari()            Sets the current record's "r3_pj_sub_hari" value
 * @method PDS_RENTUT    setR3PjBiaya()              Sets the current record's "r3_pj_biaya" value
 * @method PDS_RENTUT    setR3KurunganTahun()        Sets the current record's "r3_kurungan_tahun" value
 * @method PDS_RENTUT    setR3KurunganBulan()        Sets the current record's "r3_kurungan_bulan" value
 * @method PDS_RENTUT    setR3KurunganHari()         Sets the current record's "r3_kurungan_hari" value
 * @method PDS_RENTUT    setR3Denda()                Sets the current record's "r3_denda" value
 * @method PDS_RENTUT    setR3PutusanTambahan()      Sets the current record's "r3_putusan_tambahan" value
 * @method PDS_RENTUT    setR4PjPidanaCobaThn()      Sets the current record's "r4_pj_pidana_coba_thn" value
 * @method PDS_RENTUT    setR4PjPidanaCobaBln()      Sets the current record's "r4_pj_pidana_coba_bln" value
 * @method PDS_RENTUT    setR4PjPidanaCobaHari()     Sets the current record's "r4_pj_pidana_coba_hari" value
 * @method PDS_RENTUT    setR4PjBadanTahun()         Sets the current record's "r4_pj_badan_tahun" value
 * @method PDS_RENTUT    setR4PjBadanBulan()         Sets the current record's "r4_pj_badan_bulan" value
 * @method PDS_RENTUT    setR4PjBadanHari()          Sets the current record's "r4_pj_badan_hari" value
 * @method PDS_RENTUT    setR4PjDendaRp()            Sets the current record's "r4_pj_denda_rp" value
 * @method PDS_RENTUT    setR4PjSubTahun()           Sets the current record's "r4_pj_sub_tahun" value
 * @method PDS_RENTUT    setR4PjSubBulan()           Sets the current record's "r4_pj_sub_bulan" value
 * @method PDS_RENTUT    setR4PjSubHari()            Sets the current record's "r4_pj_sub_hari" value
 * @method PDS_RENTUT    setR4PjBiaya()              Sets the current record's "r4_pj_biaya" value
 * @method PDS_RENTUT    setR4KurunganTahun()        Sets the current record's "r4_kurungan_tahun" value
 * @method PDS_RENTUT    setR4KurunganBulan()        Sets the current record's "r4_kurungan_bulan" value
 * @method PDS_RENTUT    setR4KurunganHari()         Sets the current record's "r4_kurungan_hari" value
 * @method PDS_RENTUT    setR4Denda()                Sets the current record's "r4_denda" value
 * @method PDS_RENTUT    setR4PutusanTambahan()      Sets the current record's "r4_putusan_tambahan" value
 * @method PDS_RENTUT    setR5PjPidanaCobaThn()      Sets the current record's "r5_pj_pidana_coba_thn" value
 * @method PDS_RENTUT    setR5PjPidanaCobaBln()      Sets the current record's "r5_pj_pidana_coba_bln" value
 * @method PDS_RENTUT    setR5PjPidanaCobaHari()     Sets the current record's "r5_pj_pidana_coba_hari" value
 * @method PDS_RENTUT    setR5PjBadanTahun()         Sets the current record's "r5_pj_badan_tahun" value
 * @method PDS_RENTUT    setR5PjBadanBulan()         Sets the current record's "r5_pj_badan_bulan" value
 * @method PDS_RENTUT    setR5PjBadanHari()          Sets the current record's "r5_pj_badan_hari" value
 * @method PDS_RENTUT    setR5PjDendaRp()            Sets the current record's "r5_pj_denda_rp" value
 * @method PDS_RENTUT    setR5PjSubTahun()           Sets the current record's "r5_pj_sub_tahun" value
 * @method PDS_RENTUT    setR5PjSubBulan()           Sets the current record's "r5_pj_sub_bulan" value
 * @method PDS_RENTUT    setR5PjSubHari()            Sets the current record's "r5_pj_sub_hari" value
 * @method PDS_RENTUT    setR5PjBiaya()              Sets the current record's "r5_pj_biaya" value
 * @method PDS_RENTUT    setR5KurunganTahun()        Sets the current record's "r5_kurungan_tahun" value
 * @method PDS_RENTUT    setR5KurunganBulan()        Sets the current record's "r5_kurungan_bulan" value
 * @method PDS_RENTUT    setR5KurunganHari()         Sets the current record's "r5_kurungan_hari" value
 * @method PDS_RENTUT    setR5Denda()                Sets the current record's "r5_denda" value
 * @method PDS_RENTUT    setR5PutusanTambahan()      Sets the current record's "r5_putusan_tambahan" value
 * @method PDS_RENTUT    setR1PdnPengawasan()        Sets the current record's "r1_pdn_pengawasan" value
 * @method PDS_RENTUT    setR2PdnPengawasan()        Sets the current record's "r2_pdn_pengawasan" value
 * @method PDS_RENTUT    setR3PdnPengawasan()        Sets the current record's "r3_pdn_pengawasan" value
 * @method PDS_RENTUT    setR4PdnPengawasan()        Sets the current record's "r4_pdn_pengawasan" value
 * @method PDS_RENTUT    setR5PdnPengawasan()        Sets the current record's "r5_pdn_pengawasan" value
 * @method PDS_RENTUT    setR1JnsBebas()             Sets the current record's "r1_jns_bebas" value
 * @method PDS_RENTUT    setR2JnsBebas()             Sets the current record's "r2_jns_bebas" value
 * @method PDS_RENTUT    setR3JnsBebas()             Sets the current record's "r3_jns_bebas" value
 * @method PDS_RENTUT    setR4JnsBebas()             Sets the current record's "r4_jns_bebas" value
 * @method PDS_RENTUT    setR5JnsBebas()             Sets the current record's "r5_jns_bebas" value
 * @method PDS_RENTUT    setPDSTERSANGKA()           Sets the current record's "PDS_TERSANGKA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_RENTUT extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_RENTUT');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('r1_pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r1_pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r1_pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r1_pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r1_pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r1_kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r1_kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r1_denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r1_putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('r2_pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r2_pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r2_pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r2_pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r2_pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r2_kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r2_kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r2_denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r2_putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('r3_pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r3_pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r3_pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r3_pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r3_pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r3_kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r3_kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r3_denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r3_putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('r4_pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r4_pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r4_pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r4_pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r4_pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r4_kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r4_kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r4_denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r4_putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('r5_pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r5_pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r5_pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r5_pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r5_pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r5_kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('r5_kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('r5_denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('r5_putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('r1_pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r2_pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r3_pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r4_pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r5_pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r1_jns_bebas', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r2_jns_bebas', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r3_jns_bebas', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r4_jns_bebas', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('r5_jns_bebas', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_TERSANGKA', array(
             'local' => 'id_tersangka',
             'foreign' => 'id'));
    }
}