<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_PK_TING_REF', 'doctrine');

/**
 * BasePDS_PK_TING_REF
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pk_ting
 * @property integer $id_pdsmjnspidana
 * @property Doctrine_Collection $PDS_PERKARA
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getPkTing()           Returns the current record's "pk_ting" value
 * @method integer             getIdPdsmjnspidana()  Returns the current record's "id_pdsmjnspidana" value
 * @method Doctrine_Collection getPDSPERKARA()       Returns the current record's "PDS_PERKARA" collection
 * @method PDS_PK_TING_REF     setId()               Sets the current record's "id" value
 * @method PDS_PK_TING_REF     setPkTing()           Sets the current record's "pk_ting" value
 * @method PDS_PK_TING_REF     setIdPdsmjnspidana()  Sets the current record's "id_pdsmjnspidana" value
 * @method PDS_PK_TING_REF     setPDSPERKARA()       Sets the current record's "PDS_PERKARA" collection
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_PK_TING_REF extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_PK_TING_REF');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('pk_ting', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('id_pdsmjnspidana', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PDS_PERKARA', array(
             'local' => 'id',
             'foreign' => 'id_pk_ting'));
    }
}