<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_PERKARA', 'doctrine');

/**
 * BasePDS_PERKARA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nomor_perkara
 * @property clob $posisi_kasus
 * @property integer $id_pk_ting
 * @property string $penyidik
 * @property string $no_spdp
 * @property timestamp $tgl_spdp
 * @property string $penerima
 * @property timestamp $tgl_diterima
 * @property string $no_p16
 * @property timestamp $tgl_p16
 * @property timestamp $tgl_konsultasi
 * @property string $isi_konsultasi
 * @property string $no_p17
 * @property timestamp $tgl_p17
 * @property string $no_kirim_berkas
 * @property timestamp $tgl_kirim_berkas
 * @property string $no_p21
 * @property timestamp $tgl_p21
 * @property string $no_p21a
 * @property timestamp $tgl_p21a
 * @property string $no_kembali_berkas
 * @property timestamp $tgl_kembali_berkas
 * @property string $kd_penyelesaian
 * @property string $id_instansi
 * @property string $no_p16a
 * @property timestamp $tgl_p16a
 * @property timestamp $tgl_terima_tsk
 * @property string $no_henti_tut
 * @property timestamp $tgl_henti_tut
 * @property clob $pertimbangan_henti
 * @property string $no_limpah_pk
 * @property timestamp $tgl_diterima_pn
 * @property timestamp $tgl_tap_sidang
 * @property timestamp $tgl_baca_dakwaan
 * @property clob $isi_dakwaan
 * @property timestamp $tgl_awal_bukti
 * @property timestamp $tgl_akhir_bukti
 * @property timestamp $tgl_juk_kajari
 * @property string $isi_juk_kajari
 * @property string $no_usul_kajari
 * @property timestamp $tgl_usul_kajari
 * @property timestamp $tgl_juk_kajati
 * @property string $isi_juk_kajati
 * @property string $no_usul_kajati
 * @property timestamp $tgl_usul_kajati
 * @property timestamp $tgl_juk_ja
 * @property string $isi_juk_ja
 * @property string $no_usul_ja
 * @property timestamp $tgl_usul_ja
 * @property timestamp $tgl_baca_tut
 * @property clob $isi_tuntutan
 * @property timestamp $tgl_putusan_pn
 * @property timestamp $tgl_terima_putusan
 * @property string $kd_putusan_hukum
 * @property timestamp $tgl_putusan_hukum
 * @property string $no_barbuk
 * @property timestamp $tgl_barbuk
 * @property string $no_konsultasi
 * @property string $no_p20
 * @property timestamp $tgl_p20
 * @property string $no_optimal
 * @property timestamp $tgl_optimal
 * @property string $isi_pemeriksaan
 * @property timestamp $tgl_limpah_pk
 * @property string $lid_sumber_lap_no
 * @property timestamp $lid_sumber_lap_tgl
 * @property string $lid_sprint_no
 * @property timestamp $lid_sprint_tgl
 * @property integer $lid_selesai_pil
 * @property string $lid_selesai_no
 * @property timestamp $lid_selesai_tgl
 * @property string $dik_sprint_no
 * @property timestamp $dik_sprint_tgl
 * @property string $dik_sita_no
 * @property timestamp $dik_sita_tgl
 * @property integer $dik_selesai_pil
 * @property string $dik_selesai_no
 * @property timestamp $dik_selesai_tgl
 * @property integer $hkpn_lid_rp
 * @property integer $hkpn_lid_usd
 * @property integer $hkpn_tut_rp
 * @property integer $hkpn_tut_usd
 * @property string $dik_izin_no
 * @property timestamp $dik_izin_tgl
 * @property string $created_by
 * @property timestamp $created_time
 * @property string $created_ip
 * @property string $lastupdate_by
 * @property timestamp $lastupdate_time
 * @property string $lastupdate_ip
 * @property string $inst_satkerkd
 * @property string $terdakwa
 * @property string $p16a_jpu
 * @property string $jaksa_penuntut_umum
 * @property integer $id_perkara
 * @property string $dik_detil_jaksa
 * @property string $tut_dakwaan
 * @property string $tut_tuntutan
 * @property string $tut_amar_putusan
 * @property string $tut_p16a_nip_detil_jaksa
 * @property string $tut_p16_detil_jaksa
 * @property string $dik_pasal_disangkakan
 * @property timestamp $uheksi_tgl_putusan
 * @property timestamp $uheksi_tgl_grasi
 * @property timestamp $uheksi_tgl_pk
 * @property timestamp $uheksi_tgl_kasasi
 * @property timestamp $uheksi_tgl_banding
 * @property timestamp $tut_tgl_proses_sidang
 * @property timestamp $dik_tgl_spdp
 * @property timestamp $dik_tgl_sprint_dik
 * @property timestamp $lid_tgl_sprint_lid
 * @property timestamp $tgl_tuntut_jpu
 * @property string $isi_rentut_jpu
 * @property string $isi_pendapat_kasi
 * @property timestamp $tgl_pendapat_kasi
 * @property string $nama_berkas_dakwaan
 * @property string $nama_berkas_petunjuk
 * @property integer $uu_korupsi
 * @property integer $uang_pengganti
 * @property integer $uang_pengganti_lain
 * @property integer $mata_uang_lain
 * @property integer $sub_pengganti_tahun
 * @property integer $sub_pengganti_bulan
 * @property integer $sub_pengganti_hari
 * @property timestamp $ba_pidana_mati
 * @property timestamp $ba_pidana_coba
 * @property timestamp $ba_pidana_badan
 * @property timestamp $ba_subsidair_denda
 * @property timestamp $ba_seumur_hidup
 * @property timestamp $ba_bebas
 * @property timestamp $ba_lepas
 * @property timestamp $ba_tambahan
 * @property timestamp $ba_denda
 * @property timestamp $ba_kurungan
 * @property timestamp $ba_biaya_perkara
 * @property timestamp $ba_uang_pengganti
 * @property timestamp $ba_uang_pengganti_lain
 * @property timestamp $ba_sub_uang_pengganti
 * @property PDS_PK_TING_REF $PDS_PK_TING_REF
 * @property Doctrine_Collection $DTN_PUP_PDS
 * @property Doctrine_Collection $PDS_BARBUK
 * @property Doctrine_Collection $PDS_BERKAS
 * @property Doctrine_Collection $PDS_SETOR_DNT
 * @property Doctrine_Collection $PDS_SITA
 * @property Doctrine_Collection $PDS_TIM_JPU
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method string              getNomorPerkara()             Returns the current record's "nomor_perkara" value
 * @method clob                getPosisiKasus()              Returns the current record's "posisi_kasus" value
 * @method integer             getIdPkTing()                 Returns the current record's "id_pk_ting" value
 * @method string              getPenyidik()                 Returns the current record's "penyidik" value
 * @method string              getNoSpdp()                   Returns the current record's "no_spdp" value
 * @method timestamp           getTglSpdp()                  Returns the current record's "tgl_spdp" value
 * @method string              getPenerima()                 Returns the current record's "penerima" value
 * @method timestamp           getTglDiterima()              Returns the current record's "tgl_diterima" value
 * @method string              getNoP16()                    Returns the current record's "no_p16" value
 * @method timestamp           getTglP16()                   Returns the current record's "tgl_p16" value
 * @method timestamp           getTglKonsultasi()            Returns the current record's "tgl_konsultasi" value
 * @method string              getIsiKonsultasi()            Returns the current record's "isi_konsultasi" value
 * @method string              getNoP17()                    Returns the current record's "no_p17" value
 * @method timestamp           getTglP17()                   Returns the current record's "tgl_p17" value
 * @method string              getNoKirimBerkas()            Returns the current record's "no_kirim_berkas" value
 * @method timestamp           getTglKirimBerkas()           Returns the current record's "tgl_kirim_berkas" value
 * @method string              getNoP21()                    Returns the current record's "no_p21" value
 * @method timestamp           getTglP21()                   Returns the current record's "tgl_p21" value
 * @method string              getNoP21a()                   Returns the current record's "no_p21a" value
 * @method timestamp           getTglP21a()                  Returns the current record's "tgl_p21a" value
 * @method string              getNoKembaliBerkas()          Returns the current record's "no_kembali_berkas" value
 * @method timestamp           getTglKembaliBerkas()         Returns the current record's "tgl_kembali_berkas" value
 * @method string              getKdPenyelesaian()           Returns the current record's "kd_penyelesaian" value
 * @method string              getIdInstansi()               Returns the current record's "id_instansi" value
 * @method string              getNoP16a()                   Returns the current record's "no_p16a" value
 * @method timestamp           getTglP16a()                  Returns the current record's "tgl_p16a" value
 * @method timestamp           getTglTerimaTsk()             Returns the current record's "tgl_terima_tsk" value
 * @method string              getNoHentiTut()               Returns the current record's "no_henti_tut" value
 * @method timestamp           getTglHentiTut()              Returns the current record's "tgl_henti_tut" value
 * @method clob                getPertimbanganHenti()        Returns the current record's "pertimbangan_henti" value
 * @method string              getNoLimpahPk()               Returns the current record's "no_limpah_pk" value
 * @method timestamp           getTglDiterimaPn()            Returns the current record's "tgl_diterima_pn" value
 * @method timestamp           getTglTapSidang()             Returns the current record's "tgl_tap_sidang" value
 * @method timestamp           getTglBacaDakwaan()           Returns the current record's "tgl_baca_dakwaan" value
 * @method clob                getIsiDakwaan()               Returns the current record's "isi_dakwaan" value
 * @method timestamp           getTglAwalBukti()             Returns the current record's "tgl_awal_bukti" value
 * @method timestamp           getTglAkhirBukti()            Returns the current record's "tgl_akhir_bukti" value
 * @method timestamp           getTglJukKajari()             Returns the current record's "tgl_juk_kajari" value
 * @method string              getIsiJukKajari()             Returns the current record's "isi_juk_kajari" value
 * @method string              getNoUsulKajari()             Returns the current record's "no_usul_kajari" value
 * @method timestamp           getTglUsulKajari()            Returns the current record's "tgl_usul_kajari" value
 * @method timestamp           getTglJukKajati()             Returns the current record's "tgl_juk_kajati" value
 * @method string              getIsiJukKajati()             Returns the current record's "isi_juk_kajati" value
 * @method string              getNoUsulKajati()             Returns the current record's "no_usul_kajati" value
 * @method timestamp           getTglUsulKajati()            Returns the current record's "tgl_usul_kajati" value
 * @method timestamp           getTglJukJa()                 Returns the current record's "tgl_juk_ja" value
 * @method string              getIsiJukJa()                 Returns the current record's "isi_juk_ja" value
 * @method string              getNoUsulJa()                 Returns the current record's "no_usul_ja" value
 * @method timestamp           getTglUsulJa()                Returns the current record's "tgl_usul_ja" value
 * @method timestamp           getTglBacaTut()               Returns the current record's "tgl_baca_tut" value
 * @method clob                getIsiTuntutan()              Returns the current record's "isi_tuntutan" value
 * @method timestamp           getTglPutusanPn()             Returns the current record's "tgl_putusan_pn" value
 * @method timestamp           getTglTerimaPutusan()         Returns the current record's "tgl_terima_putusan" value
 * @method string              getKdPutusanHukum()           Returns the current record's "kd_putusan_hukum" value
 * @method timestamp           getTglPutusanHukum()          Returns the current record's "tgl_putusan_hukum" value
 * @method string              getNoBarbuk()                 Returns the current record's "no_barbuk" value
 * @method timestamp           getTglBarbuk()                Returns the current record's "tgl_barbuk" value
 * @method string              getNoKonsultasi()             Returns the current record's "no_konsultasi" value
 * @method string              getNoP20()                    Returns the current record's "no_p20" value
 * @method timestamp           getTglP20()                   Returns the current record's "tgl_p20" value
 * @method string              getNoOptimal()                Returns the current record's "no_optimal" value
 * @method timestamp           getTglOptimal()               Returns the current record's "tgl_optimal" value
 * @method string              getIsiPemeriksaan()           Returns the current record's "isi_pemeriksaan" value
 * @method timestamp           getTglLimpahPk()              Returns the current record's "tgl_limpah_pk" value
 * @method string              getLidSumberLapNo()           Returns the current record's "lid_sumber_lap_no" value
 * @method timestamp           getLidSumberLapTgl()          Returns the current record's "lid_sumber_lap_tgl" value
 * @method string              getLidSprintNo()              Returns the current record's "lid_sprint_no" value
 * @method timestamp           getLidSprintTgl()             Returns the current record's "lid_sprint_tgl" value
 * @method integer             getLidSelesaiPil()            Returns the current record's "lid_selesai_pil" value
 * @method string              getLidSelesaiNo()             Returns the current record's "lid_selesai_no" value
 * @method timestamp           getLidSelesaiTgl()            Returns the current record's "lid_selesai_tgl" value
 * @method string              getDikSprintNo()              Returns the current record's "dik_sprint_no" value
 * @method timestamp           getDikSprintTgl()             Returns the current record's "dik_sprint_tgl" value
 * @method string              getDikSitaNo()                Returns the current record's "dik_sita_no" value
 * @method timestamp           getDikSitaTgl()               Returns the current record's "dik_sita_tgl" value
 * @method integer             getDikSelesaiPil()            Returns the current record's "dik_selesai_pil" value
 * @method string              getDikSelesaiNo()             Returns the current record's "dik_selesai_no" value
 * @method timestamp           getDikSelesaiTgl()            Returns the current record's "dik_selesai_tgl" value
 * @method integer             getHkpnLidRp()                Returns the current record's "hkpn_lid_rp" value
 * @method integer             getHkpnLidUsd()               Returns the current record's "hkpn_lid_usd" value
 * @method integer             getHkpnTutRp()                Returns the current record's "hkpn_tut_rp" value
 * @method integer             getHkpnTutUsd()               Returns the current record's "hkpn_tut_usd" value
 * @method string              getDikIzinNo()                Returns the current record's "dik_izin_no" value
 * @method timestamp           getDikIzinTgl()               Returns the current record's "dik_izin_tgl" value
 * @method string              getCreatedBy()                Returns the current record's "created_by" value
 * @method timestamp           getCreatedTime()              Returns the current record's "created_time" value
 * @method string              getCreatedIp()                Returns the current record's "created_ip" value
 * @method string              getLastupdateBy()             Returns the current record's "lastupdate_by" value
 * @method timestamp           getLastupdateTime()           Returns the current record's "lastupdate_time" value
 * @method string              getLastupdateIp()             Returns the current record's "lastupdate_ip" value
 * @method string              getInstSatkerkd()             Returns the current record's "inst_satkerkd" value
 * @method string              getTerdakwa()                 Returns the current record's "terdakwa" value
 * @method string              getP16aJpu()                  Returns the current record's "p16a_jpu" value
 * @method string              getJaksaPenuntutUmum()        Returns the current record's "jaksa_penuntut_umum" value
 * @method integer             getIdPerkara()                Returns the current record's "id_perkara" value
 * @method string              getDikDetilJaksa()            Returns the current record's "dik_detil_jaksa" value
 * @method string              getTutDakwaan()               Returns the current record's "tut_dakwaan" value
 * @method string              getTutTuntutan()              Returns the current record's "tut_tuntutan" value
 * @method string              getTutAmarPutusan()           Returns the current record's "tut_amar_putusan" value
 * @method string              getTutP16aNipDetilJaksa()     Returns the current record's "tut_p16a_nip_detil_jaksa" value
 * @method string              getTutP16DetilJaksa()         Returns the current record's "tut_p16_detil_jaksa" value
 * @method string              getDikPasalDisangkakan()      Returns the current record's "dik_pasal_disangkakan" value
 * @method timestamp           getUheksiTglPutusan()         Returns the current record's "uheksi_tgl_putusan" value
 * @method timestamp           getUheksiTglGrasi()           Returns the current record's "uheksi_tgl_grasi" value
 * @method timestamp           getUheksiTglPk()              Returns the current record's "uheksi_tgl_pk" value
 * @method timestamp           getUheksiTglKasasi()          Returns the current record's "uheksi_tgl_kasasi" value
 * @method timestamp           getUheksiTglBanding()         Returns the current record's "uheksi_tgl_banding" value
 * @method timestamp           getTutTglProsesSidang()       Returns the current record's "tut_tgl_proses_sidang" value
 * @method timestamp           getDikTglSpdp()               Returns the current record's "dik_tgl_spdp" value
 * @method timestamp           getDikTglSprintDik()          Returns the current record's "dik_tgl_sprint_dik" value
 * @method timestamp           getLidTglSprintLid()          Returns the current record's "lid_tgl_sprint_lid" value
 * @method timestamp           getTglTuntutJpu()             Returns the current record's "tgl_tuntut_jpu" value
 * @method string              getIsiRentutJpu()             Returns the current record's "isi_rentut_jpu" value
 * @method string              getIsiPendapatKasi()          Returns the current record's "isi_pendapat_kasi" value
 * @method timestamp           getTglPendapatKasi()          Returns the current record's "tgl_pendapat_kasi" value
 * @method string              getNamaBerkasDakwaan()        Returns the current record's "nama_berkas_dakwaan" value
 * @method string              getNamaBerkasPetunjuk()       Returns the current record's "nama_berkas_petunjuk" value
 * @method integer             getUuKorupsi()                Returns the current record's "uu_korupsi" value
 * @method integer             getUangPengganti()            Returns the current record's "uang_pengganti" value
 * @method integer             getUangPenggantiLain()        Returns the current record's "uang_pengganti_lain" value
 * @method integer             getMataUangLain()             Returns the current record's "mata_uang_lain" value
 * @method integer             getSubPenggantiTahun()        Returns the current record's "sub_pengganti_tahun" value
 * @method integer             getSubPenggantiBulan()        Returns the current record's "sub_pengganti_bulan" value
 * @method integer             getSubPenggantiHari()         Returns the current record's "sub_pengganti_hari" value
 * @method timestamp           getBaPidanaMati()             Returns the current record's "ba_pidana_mati" value
 * @method timestamp           getBaPidanaCoba()             Returns the current record's "ba_pidana_coba" value
 * @method timestamp           getBaPidanaBadan()            Returns the current record's "ba_pidana_badan" value
 * @method timestamp           getBaSubsidairDenda()         Returns the current record's "ba_subsidair_denda" value
 * @method timestamp           getBaSeumurHidup()            Returns the current record's "ba_seumur_hidup" value
 * @method timestamp           getBaBebas()                  Returns the current record's "ba_bebas" value
 * @method timestamp           getBaLepas()                  Returns the current record's "ba_lepas" value
 * @method timestamp           getBaTambahan()               Returns the current record's "ba_tambahan" value
 * @method timestamp           getBaDenda()                  Returns the current record's "ba_denda" value
 * @method timestamp           getBaKurungan()               Returns the current record's "ba_kurungan" value
 * @method timestamp           getBaBiayaPerkara()           Returns the current record's "ba_biaya_perkara" value
 * @method timestamp           getBaUangPengganti()          Returns the current record's "ba_uang_pengganti" value
 * @method timestamp           getBaUangPenggantiLain()      Returns the current record's "ba_uang_pengganti_lain" value
 * @method timestamp           getBaSubUangPengganti()       Returns the current record's "ba_sub_uang_pengganti" value
 * @method PDS_PK_TING_REF     getPDSPKTINGREF()             Returns the current record's "PDS_PK_TING_REF" value
 * @method Doctrine_Collection getDTNPUPPDS()                Returns the current record's "DTN_PUP_PDS" collection
 * @method Doctrine_Collection getPDSBARBUK()                Returns the current record's "PDS_BARBUK" collection
 * @method Doctrine_Collection getPDSBERKAS()                Returns the current record's "PDS_BERKAS" collection
 * @method Doctrine_Collection getPDSSETORDNT()              Returns the current record's "PDS_SETOR_DNT" collection
 * @method Doctrine_Collection getPDSSITA()                  Returns the current record's "PDS_SITA" collection
 * @method Doctrine_Collection getPDSTIMJPU()                Returns the current record's "PDS_TIM_JPU" collection
 * @method PDS_PERKARA         setId()                       Sets the current record's "id" value
 * @method PDS_PERKARA         setNomorPerkara()             Sets the current record's "nomor_perkara" value
 * @method PDS_PERKARA         setPosisiKasus()              Sets the current record's "posisi_kasus" value
 * @method PDS_PERKARA         setIdPkTing()                 Sets the current record's "id_pk_ting" value
 * @method PDS_PERKARA         setPenyidik()                 Sets the current record's "penyidik" value
 * @method PDS_PERKARA         setNoSpdp()                   Sets the current record's "no_spdp" value
 * @method PDS_PERKARA         setTglSpdp()                  Sets the current record's "tgl_spdp" value
 * @method PDS_PERKARA         setPenerima()                 Sets the current record's "penerima" value
 * @method PDS_PERKARA         setTglDiterima()              Sets the current record's "tgl_diterima" value
 * @method PDS_PERKARA         setNoP16()                    Sets the current record's "no_p16" value
 * @method PDS_PERKARA         setTglP16()                   Sets the current record's "tgl_p16" value
 * @method PDS_PERKARA         setTglKonsultasi()            Sets the current record's "tgl_konsultasi" value
 * @method PDS_PERKARA         setIsiKonsultasi()            Sets the current record's "isi_konsultasi" value
 * @method PDS_PERKARA         setNoP17()                    Sets the current record's "no_p17" value
 * @method PDS_PERKARA         setTglP17()                   Sets the current record's "tgl_p17" value
 * @method PDS_PERKARA         setNoKirimBerkas()            Sets the current record's "no_kirim_berkas" value
 * @method PDS_PERKARA         setTglKirimBerkas()           Sets the current record's "tgl_kirim_berkas" value
 * @method PDS_PERKARA         setNoP21()                    Sets the current record's "no_p21" value
 * @method PDS_PERKARA         setTglP21()                   Sets the current record's "tgl_p21" value
 * @method PDS_PERKARA         setNoP21a()                   Sets the current record's "no_p21a" value
 * @method PDS_PERKARA         setTglP21a()                  Sets the current record's "tgl_p21a" value
 * @method PDS_PERKARA         setNoKembaliBerkas()          Sets the current record's "no_kembali_berkas" value
 * @method PDS_PERKARA         setTglKembaliBerkas()         Sets the current record's "tgl_kembali_berkas" value
 * @method PDS_PERKARA         setKdPenyelesaian()           Sets the current record's "kd_penyelesaian" value
 * @method PDS_PERKARA         setIdInstansi()               Sets the current record's "id_instansi" value
 * @method PDS_PERKARA         setNoP16a()                   Sets the current record's "no_p16a" value
 * @method PDS_PERKARA         setTglP16a()                  Sets the current record's "tgl_p16a" value
 * @method PDS_PERKARA         setTglTerimaTsk()             Sets the current record's "tgl_terima_tsk" value
 * @method PDS_PERKARA         setNoHentiTut()               Sets the current record's "no_henti_tut" value
 * @method PDS_PERKARA         setTglHentiTut()              Sets the current record's "tgl_henti_tut" value
 * @method PDS_PERKARA         setPertimbanganHenti()        Sets the current record's "pertimbangan_henti" value
 * @method PDS_PERKARA         setNoLimpahPk()               Sets the current record's "no_limpah_pk" value
 * @method PDS_PERKARA         setTglDiterimaPn()            Sets the current record's "tgl_diterima_pn" value
 * @method PDS_PERKARA         setTglTapSidang()             Sets the current record's "tgl_tap_sidang" value
 * @method PDS_PERKARA         setTglBacaDakwaan()           Sets the current record's "tgl_baca_dakwaan" value
 * @method PDS_PERKARA         setIsiDakwaan()               Sets the current record's "isi_dakwaan" value
 * @method PDS_PERKARA         setTglAwalBukti()             Sets the current record's "tgl_awal_bukti" value
 * @method PDS_PERKARA         setTglAkhirBukti()            Sets the current record's "tgl_akhir_bukti" value
 * @method PDS_PERKARA         setTglJukKajari()             Sets the current record's "tgl_juk_kajari" value
 * @method PDS_PERKARA         setIsiJukKajari()             Sets the current record's "isi_juk_kajari" value
 * @method PDS_PERKARA         setNoUsulKajari()             Sets the current record's "no_usul_kajari" value
 * @method PDS_PERKARA         setTglUsulKajari()            Sets the current record's "tgl_usul_kajari" value
 * @method PDS_PERKARA         setTglJukKajati()             Sets the current record's "tgl_juk_kajati" value
 * @method PDS_PERKARA         setIsiJukKajati()             Sets the current record's "isi_juk_kajati" value
 * @method PDS_PERKARA         setNoUsulKajati()             Sets the current record's "no_usul_kajati" value
 * @method PDS_PERKARA         setTglUsulKajati()            Sets the current record's "tgl_usul_kajati" value
 * @method PDS_PERKARA         setTglJukJa()                 Sets the current record's "tgl_juk_ja" value
 * @method PDS_PERKARA         setIsiJukJa()                 Sets the current record's "isi_juk_ja" value
 * @method PDS_PERKARA         setNoUsulJa()                 Sets the current record's "no_usul_ja" value
 * @method PDS_PERKARA         setTglUsulJa()                Sets the current record's "tgl_usul_ja" value
 * @method PDS_PERKARA         setTglBacaTut()               Sets the current record's "tgl_baca_tut" value
 * @method PDS_PERKARA         setIsiTuntutan()              Sets the current record's "isi_tuntutan" value
 * @method PDS_PERKARA         setTglPutusanPn()             Sets the current record's "tgl_putusan_pn" value
 * @method PDS_PERKARA         setTglTerimaPutusan()         Sets the current record's "tgl_terima_putusan" value
 * @method PDS_PERKARA         setKdPutusanHukum()           Sets the current record's "kd_putusan_hukum" value
 * @method PDS_PERKARA         setTglPutusanHukum()          Sets the current record's "tgl_putusan_hukum" value
 * @method PDS_PERKARA         setNoBarbuk()                 Sets the current record's "no_barbuk" value
 * @method PDS_PERKARA         setTglBarbuk()                Sets the current record's "tgl_barbuk" value
 * @method PDS_PERKARA         setNoKonsultasi()             Sets the current record's "no_konsultasi" value
 * @method PDS_PERKARA         setNoP20()                    Sets the current record's "no_p20" value
 * @method PDS_PERKARA         setTglP20()                   Sets the current record's "tgl_p20" value
 * @method PDS_PERKARA         setNoOptimal()                Sets the current record's "no_optimal" value
 * @method PDS_PERKARA         setTglOptimal()               Sets the current record's "tgl_optimal" value
 * @method PDS_PERKARA         setIsiPemeriksaan()           Sets the current record's "isi_pemeriksaan" value
 * @method PDS_PERKARA         setTglLimpahPk()              Sets the current record's "tgl_limpah_pk" value
 * @method PDS_PERKARA         setLidSumberLapNo()           Sets the current record's "lid_sumber_lap_no" value
 * @method PDS_PERKARA         setLidSumberLapTgl()          Sets the current record's "lid_sumber_lap_tgl" value
 * @method PDS_PERKARA         setLidSprintNo()              Sets the current record's "lid_sprint_no" value
 * @method PDS_PERKARA         setLidSprintTgl()             Sets the current record's "lid_sprint_tgl" value
 * @method PDS_PERKARA         setLidSelesaiPil()            Sets the current record's "lid_selesai_pil" value
 * @method PDS_PERKARA         setLidSelesaiNo()             Sets the current record's "lid_selesai_no" value
 * @method PDS_PERKARA         setLidSelesaiTgl()            Sets the current record's "lid_selesai_tgl" value
 * @method PDS_PERKARA         setDikSprintNo()              Sets the current record's "dik_sprint_no" value
 * @method PDS_PERKARA         setDikSprintTgl()             Sets the current record's "dik_sprint_tgl" value
 * @method PDS_PERKARA         setDikSitaNo()                Sets the current record's "dik_sita_no" value
 * @method PDS_PERKARA         setDikSitaTgl()               Sets the current record's "dik_sita_tgl" value
 * @method PDS_PERKARA         setDikSelesaiPil()            Sets the current record's "dik_selesai_pil" value
 * @method PDS_PERKARA         setDikSelesaiNo()             Sets the current record's "dik_selesai_no" value
 * @method PDS_PERKARA         setDikSelesaiTgl()            Sets the current record's "dik_selesai_tgl" value
 * @method PDS_PERKARA         setHkpnLidRp()                Sets the current record's "hkpn_lid_rp" value
 * @method PDS_PERKARA         setHkpnLidUsd()               Sets the current record's "hkpn_lid_usd" value
 * @method PDS_PERKARA         setHkpnTutRp()                Sets the current record's "hkpn_tut_rp" value
 * @method PDS_PERKARA         setHkpnTutUsd()               Sets the current record's "hkpn_tut_usd" value
 * @method PDS_PERKARA         setDikIzinNo()                Sets the current record's "dik_izin_no" value
 * @method PDS_PERKARA         setDikIzinTgl()               Sets the current record's "dik_izin_tgl" value
 * @method PDS_PERKARA         setCreatedBy()                Sets the current record's "created_by" value
 * @method PDS_PERKARA         setCreatedTime()              Sets the current record's "created_time" value
 * @method PDS_PERKARA         setCreatedIp()                Sets the current record's "created_ip" value
 * @method PDS_PERKARA         setLastupdateBy()             Sets the current record's "lastupdate_by" value
 * @method PDS_PERKARA         setLastupdateTime()           Sets the current record's "lastupdate_time" value
 * @method PDS_PERKARA         setLastupdateIp()             Sets the current record's "lastupdate_ip" value
 * @method PDS_PERKARA         setInstSatkerkd()             Sets the current record's "inst_satkerkd" value
 * @method PDS_PERKARA         setTerdakwa()                 Sets the current record's "terdakwa" value
 * @method PDS_PERKARA         setP16aJpu()                  Sets the current record's "p16a_jpu" value
 * @method PDS_PERKARA         setJaksaPenuntutUmum()        Sets the current record's "jaksa_penuntut_umum" value
 * @method PDS_PERKARA         setIdPerkara()                Sets the current record's "id_perkara" value
 * @method PDS_PERKARA         setDikDetilJaksa()            Sets the current record's "dik_detil_jaksa" value
 * @method PDS_PERKARA         setTutDakwaan()               Sets the current record's "tut_dakwaan" value
 * @method PDS_PERKARA         setTutTuntutan()              Sets the current record's "tut_tuntutan" value
 * @method PDS_PERKARA         setTutAmarPutusan()           Sets the current record's "tut_amar_putusan" value
 * @method PDS_PERKARA         setTutP16aNipDetilJaksa()     Sets the current record's "tut_p16a_nip_detil_jaksa" value
 * @method PDS_PERKARA         setTutP16DetilJaksa()         Sets the current record's "tut_p16_detil_jaksa" value
 * @method PDS_PERKARA         setDikPasalDisangkakan()      Sets the current record's "dik_pasal_disangkakan" value
 * @method PDS_PERKARA         setUheksiTglPutusan()         Sets the current record's "uheksi_tgl_putusan" value
 * @method PDS_PERKARA         setUheksiTglGrasi()           Sets the current record's "uheksi_tgl_grasi" value
 * @method PDS_PERKARA         setUheksiTglPk()              Sets the current record's "uheksi_tgl_pk" value
 * @method PDS_PERKARA         setUheksiTglKasasi()          Sets the current record's "uheksi_tgl_kasasi" value
 * @method PDS_PERKARA         setUheksiTglBanding()         Sets the current record's "uheksi_tgl_banding" value
 * @method PDS_PERKARA         setTutTglProsesSidang()       Sets the current record's "tut_tgl_proses_sidang" value
 * @method PDS_PERKARA         setDikTglSpdp()               Sets the current record's "dik_tgl_spdp" value
 * @method PDS_PERKARA         setDikTglSprintDik()          Sets the current record's "dik_tgl_sprint_dik" value
 * @method PDS_PERKARA         setLidTglSprintLid()          Sets the current record's "lid_tgl_sprint_lid" value
 * @method PDS_PERKARA         setTglTuntutJpu()             Sets the current record's "tgl_tuntut_jpu" value
 * @method PDS_PERKARA         setIsiRentutJpu()             Sets the current record's "isi_rentut_jpu" value
 * @method PDS_PERKARA         setIsiPendapatKasi()          Sets the current record's "isi_pendapat_kasi" value
 * @method PDS_PERKARA         setTglPendapatKasi()          Sets the current record's "tgl_pendapat_kasi" value
 * @method PDS_PERKARA         setNamaBerkasDakwaan()        Sets the current record's "nama_berkas_dakwaan" value
 * @method PDS_PERKARA         setNamaBerkasPetunjuk()       Sets the current record's "nama_berkas_petunjuk" value
 * @method PDS_PERKARA         setUuKorupsi()                Sets the current record's "uu_korupsi" value
 * @method PDS_PERKARA         setUangPengganti()            Sets the current record's "uang_pengganti" value
 * @method PDS_PERKARA         setUangPenggantiLain()        Sets the current record's "uang_pengganti_lain" value
 * @method PDS_PERKARA         setMataUangLain()             Sets the current record's "mata_uang_lain" value
 * @method PDS_PERKARA         setSubPenggantiTahun()        Sets the current record's "sub_pengganti_tahun" value
 * @method PDS_PERKARA         setSubPenggantiBulan()        Sets the current record's "sub_pengganti_bulan" value
 * @method PDS_PERKARA         setSubPenggantiHari()         Sets the current record's "sub_pengganti_hari" value
 * @method PDS_PERKARA         setBaPidanaMati()             Sets the current record's "ba_pidana_mati" value
 * @method PDS_PERKARA         setBaPidanaCoba()             Sets the current record's "ba_pidana_coba" value
 * @method PDS_PERKARA         setBaPidanaBadan()            Sets the current record's "ba_pidana_badan" value
 * @method PDS_PERKARA         setBaSubsidairDenda()         Sets the current record's "ba_subsidair_denda" value
 * @method PDS_PERKARA         setBaSeumurHidup()            Sets the current record's "ba_seumur_hidup" value
 * @method PDS_PERKARA         setBaBebas()                  Sets the current record's "ba_bebas" value
 * @method PDS_PERKARA         setBaLepas()                  Sets the current record's "ba_lepas" value
 * @method PDS_PERKARA         setBaTambahan()               Sets the current record's "ba_tambahan" value
 * @method PDS_PERKARA         setBaDenda()                  Sets the current record's "ba_denda" value
 * @method PDS_PERKARA         setBaKurungan()               Sets the current record's "ba_kurungan" value
 * @method PDS_PERKARA         setBaBiayaPerkara()           Sets the current record's "ba_biaya_perkara" value
 * @method PDS_PERKARA         setBaUangPengganti()          Sets the current record's "ba_uang_pengganti" value
 * @method PDS_PERKARA         setBaUangPenggantiLain()      Sets the current record's "ba_uang_pengganti_lain" value
 * @method PDS_PERKARA         setBaSubUangPengganti()       Sets the current record's "ba_sub_uang_pengganti" value
 * @method PDS_PERKARA         setPDSPKTINGREF()             Sets the current record's "PDS_PK_TING_REF" value
 * @method PDS_PERKARA         setDTNPUPPDS()                Sets the current record's "DTN_PUP_PDS" collection
 * @method PDS_PERKARA         setPDSBARBUK()                Sets the current record's "PDS_BARBUK" collection
 * @method PDS_PERKARA         setPDSBERKAS()                Sets the current record's "PDS_BERKAS" collection
 * @method PDS_PERKARA         setPDSSETORDNT()              Sets the current record's "PDS_SETOR_DNT" collection
 * @method PDS_PERKARA         setPDSSITA()                  Sets the current record's "PDS_SITA" collection
 * @method PDS_PERKARA         setPDSTIMJPU()                Sets the current record's "PDS_TIM_JPU" collection
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_PERKARA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_PERKARA');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nomor_perkara', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('posisi_kasus', 'clob', 4000, array(
             'notnull' => false,
             'type' => 'clob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('id_pk_ting', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('penyidik', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('no_spdp', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_spdp', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('penerima', 'string', 80, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 80,
             ));
        $this->hasColumn('tgl_diterima', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_p16', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p16', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_konsultasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_konsultasi', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('no_p17', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p17', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_kirim_berkas', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_kirim_berkas', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_p21', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p21', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_p21a', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p21a', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_kembali_berkas', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_kembali_berkas', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('kd_penyelesaian', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('id_instansi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('no_p16a', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p16a', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_terima_tsk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_henti_tut', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_henti_tut', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pertimbangan_henti', 'clob', 4000, array(
             'notnull' => false,
             'type' => 'clob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('no_limpah_pk', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_diterima_pn', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_tap_sidang', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_baca_dakwaan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_dakwaan', 'clob', 4000, array(
             'notnull' => false,
             'type' => 'clob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tgl_awal_bukti', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_akhir_bukti', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_juk_kajari', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_juk_kajari', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('no_usul_kajari', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_usul_kajari', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_juk_kajati', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_juk_kajati', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('no_usul_kajati', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_usul_kajati', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_juk_ja', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_juk_ja', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('no_usul_ja', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_usul_ja', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_baca_tut', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_tuntutan', 'clob', 4000, array(
             'notnull' => false,
             'type' => 'clob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tgl_putusan_pn', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_terima_putusan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('kd_putusan_hukum', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('tgl_putusan_hukum', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_barbuk', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tgl_barbuk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_konsultasi', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('no_p20', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_p20', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_optimal', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('tgl_optimal', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_pemeriksaan', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tgl_limpah_pk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lid_sumber_lap_no', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('lid_sumber_lap_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lid_sprint_no', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('lid_sprint_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lid_selesai_pil', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('lid_selesai_no', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('lid_selesai_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dik_sprint_no', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('dik_sprint_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dik_sita_no', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('dik_sita_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dik_selesai_pil', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('dik_selesai_no', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('dik_selesai_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('hkpn_lid_rp', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('hkpn_lid_usd', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('hkpn_tut_rp', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('hkpn_tut_usd', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('dik_izin_no', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('dik_izin_tgl', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('created_by', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('created_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('created_ip', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('lastupdate_by', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('lastupdate_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lastupdate_ip', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_satkerkd', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('terdakwa', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('p16a_jpu', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('jaksa_penuntut_umum', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('dik_detil_jaksa', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tut_dakwaan', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tut_tuntutan', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tut_amar_putusan', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tut_p16a_nip_detil_jaksa', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tut_p16_detil_jaksa', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('dik_pasal_disangkakan', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('uheksi_tgl_putusan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('uheksi_tgl_grasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('uheksi_tgl_pk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('uheksi_tgl_kasasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('uheksi_tgl_banding', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tut_tgl_proses_sidang', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dik_tgl_spdp', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('dik_tgl_sprint_dik', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lid_tgl_sprint_lid', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_tuntut_jpu', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_rentut_jpu', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('isi_pendapat_kasi', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('tgl_pendapat_kasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('nama_berkas_dakwaan', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('nama_berkas_petunjuk', 'string', 255, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('uu_korupsi', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('uang_pengganti', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('uang_pengganti_lain', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('mata_uang_lain', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('sub_pengganti_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('sub_pengganti_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('sub_pengganti_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('ba_pidana_mati', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_pidana_coba', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_pidana_badan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_subsidair_denda', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_seumur_hidup', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_bebas', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_lepas', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_tambahan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_denda', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_kurungan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_biaya_perkara', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_uang_pengganti', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_uang_pengganti_lain', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ba_sub_uang_pengganti', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_PK_TING_REF', array(
             'local' => 'id_pk_ting',
             'foreign' => 'id'));

        $this->hasMany('DTN_PUP_PDS', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));

        $this->hasMany('PDS_BARBUK', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));

        $this->hasMany('PDS_BERKAS', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));

        $this->hasMany('PDS_SETOR_DNT', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));

        $this->hasMany('PDS_SITA', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));

        $this->hasMany('PDS_TIM_JPU', array(
             'local' => 'id',
             'foreign' => 'id_perkara'));
    }
}