<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_TIM_JPU', 'doctrine');

/**
 * BasePDS_TIM_JPU
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_perkara
 * @property string $nip_pegawai
 * @property integer $peneliti
 * @property integer $penuntut
 * @property integer $eksekutor
 * @property integer $penyelidik
 * @property integer $penyidik
 * @property integer $upaya_hukum
 * @property string $nama
 * @property string $jabatan
 * @property string $golongan
 * @property integer $flag
 * @property PDS_PERKARA $PDS_PERKARA
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getIdPerkara()   Returns the current record's "id_perkara" value
 * @method string      getNipPegawai()  Returns the current record's "nip_pegawai" value
 * @method integer     getPeneliti()    Returns the current record's "peneliti" value
 * @method integer     getPenuntut()    Returns the current record's "penuntut" value
 * @method integer     getEksekutor()   Returns the current record's "eksekutor" value
 * @method integer     getPenyelidik()  Returns the current record's "penyelidik" value
 * @method integer     getPenyidik()    Returns the current record's "penyidik" value
 * @method integer     getUpayaHukum()  Returns the current record's "upaya_hukum" value
 * @method string      getNama()        Returns the current record's "nama" value
 * @method string      getJabatan()     Returns the current record's "jabatan" value
 * @method string      getGolongan()    Returns the current record's "golongan" value
 * @method integer     getFlag()        Returns the current record's "flag" value
 * @method PDS_PERKARA getPDSPERKARA()  Returns the current record's "PDS_PERKARA" value
 * @method PDS_TIM_JPU setId()          Sets the current record's "id" value
 * @method PDS_TIM_JPU setIdPerkara()   Sets the current record's "id_perkara" value
 * @method PDS_TIM_JPU setNipPegawai()  Sets the current record's "nip_pegawai" value
 * @method PDS_TIM_JPU setPeneliti()    Sets the current record's "peneliti" value
 * @method PDS_TIM_JPU setPenuntut()    Sets the current record's "penuntut" value
 * @method PDS_TIM_JPU setEksekutor()   Sets the current record's "eksekutor" value
 * @method PDS_TIM_JPU setPenyelidik()  Sets the current record's "penyelidik" value
 * @method PDS_TIM_JPU setPenyidik()    Sets the current record's "penyidik" value
 * @method PDS_TIM_JPU setUpayaHukum()  Sets the current record's "upaya_hukum" value
 * @method PDS_TIM_JPU setNama()        Sets the current record's "nama" value
 * @method PDS_TIM_JPU setJabatan()     Sets the current record's "jabatan" value
 * @method PDS_TIM_JPU setGolongan()    Sets the current record's "golongan" value
 * @method PDS_TIM_JPU setFlag()        Sets the current record's "flag" value
 * @method PDS_TIM_JPU setPDSPERKARA()  Sets the current record's "PDS_PERKARA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_TIM_JPU extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_TIM_JPU');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nip_pegawai', 'string', 18, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('peneliti', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('penuntut', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('eksekutor', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('penyelidik', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('penyidik', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('upaya_hukum', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('nama', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('jabatan', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('golongan', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('flag', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_PERKARA', array(
             'local' => 'id_perkara',
             'foreign' => 'id'));
    }
}