<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDM_TERSANGKA', 'doctrine');

/**
 * BasePDM_TERSANGKA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nama
 * @property string $tempat_lahir
 * @property timestamp $tgl_lahir
 * @property integer $jkl
 * @property string $kewarganegaraan
 * @property string $alamat
 * @property string $pekerjaan
 * @property integer $id_perkara
 * @property timestamp $ph_jpu_mulai
 * @property timestamp $ph_jpu_selesai
 * @property string $ph_jpu_lokasi
 * @property timestamp $ph_hakim1_mulai
 * @property timestamp $ph_hakim1_selesai
 * @property string $ph_hakim1_lokasi
 * @property timestamp $ph_hakim2_mulai
 * @property timestamp $ph_hakim2_selesai
 * @property string $ph_hakim2_lokasi
 * @property timestamp $ph_pengalihan_mulai
 * @property timestamp $ph_pengalihan_selesai
 * @property string $ph_pengalihan_lokasi
 * @property timestamp $ph_pembantaran_mulai
 * @property timestamp $ph_pembantaran_selesai
 * @property string $ph_pembantaran_lokasi
 * @property integer $jenis_putusan
 * @property string $pj_pidana_coba
 * @property string $pj_masa_coba
 * @property integer $pj_badan_tahun
 * @property integer $pj_badan_bulan
 * @property integer $pj_badan_hari
 * @property decimal $pj_denda_rp
 * @property integer $pj_sub_tahun
 * @property integer $pj_sub_bulan
 * @property integer $pj_sub_hari
 * @property decimal $pj_biaya
 * @property integer $kurungan_tahun
 * @property integer $kurungan_bulan
 * @property integer $kurungan_hari
 * @property decimal $denda
 * @property string $putusan_tambahan
 * @property integer $sikap_jaksa
 * @property integer $sikap_terdakwa
 * @property timestamp $ph_penyidik_mulai
 * @property timestamp $ph_penyidik_selesai
 * @property string $ph_penyidik_lokasi
 * @property timestamp $ph_kejari_mulai
 * @property timestamp $ph_kejari_selesai
 * @property string $ph_kejari_lokasi
 * @property timestamp $ph_pn_mulai
 * @property timestamp $ph_pn_selesai
 * @property string $ph_pn_lokasi
 * @property integer $umur
 * @property integer $id_agama
 * @property integer $pendidikan
 * @property integer $putusan_tetap
 * @property timestamp $tgl_eksekusi
 * @property integer $putusan_upaya_hukum
 * @property timestamp $tgl_ptsn_bndg_ksasi
 * @property timestamp $tgl_ptsn_pk_grasi
 * @property timestamp $tgl_eksekusi_pk_grasi
 * @property integer $pj_pidana_coba_thn
 * @property integer $pj_pidana_coba_bln
 * @property integer $pj_pidana_coba_hari
 * @property string $idoff
 * @property integer $rentut_jaksajpu
 * @property integer $rentut_kasipidum
 * @property integer $rentut_kejari
 * @property integer $rentut_kejati
 * @property integer $rentut_kejagung
 * @property integer $pdn_pengawasan
 * @property MS_AGAMA $MS_AGAMA
 * @property PDM_PERKARA $PDM_PERKARA
 * @property MS_PENDIDIKAN $MS_PENDIDIKAN
 * @property MS_JNSKELAMIN $MS_JNSKELAMIN
 * @property Doctrine_Collection $PDM_PASAL
 * @property Doctrine_Collection $PDM_UPAYA_BANDING
 * @property Doctrine_Collection $PDM_UPAYA_GRASI
 * @property Doctrine_Collection $PDM_UPAYA_KASASI
 * @property Doctrine_Collection $PDM_UPAYA_PK
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getNama()                   Returns the current record's "nama" value
 * @method string              getTempatLahir()            Returns the current record's "tempat_lahir" value
 * @method timestamp           getTglLahir()               Returns the current record's "tgl_lahir" value
 * @method integer             getJkl()                    Returns the current record's "jkl" value
 * @method string              getKewarganegaraan()        Returns the current record's "kewarganegaraan" value
 * @method string              getAlamat()                 Returns the current record's "alamat" value
 * @method string              getPekerjaan()              Returns the current record's "pekerjaan" value
 * @method integer             getIdPerkara()              Returns the current record's "id_perkara" value
 * @method timestamp           getPhJpuMulai()             Returns the current record's "ph_jpu_mulai" value
 * @method timestamp           getPhJpuSelesai()           Returns the current record's "ph_jpu_selesai" value
 * @method string              getPhJpuLokasi()            Returns the current record's "ph_jpu_lokasi" value
 * @method timestamp           getPhHakim1Mulai()          Returns the current record's "ph_hakim1_mulai" value
 * @method timestamp           getPhHakim1Selesai()        Returns the current record's "ph_hakim1_selesai" value
 * @method string              getPhHakim1Lokasi()         Returns the current record's "ph_hakim1_lokasi" value
 * @method timestamp           getPhHakim2Mulai()          Returns the current record's "ph_hakim2_mulai" value
 * @method timestamp           getPhHakim2Selesai()        Returns the current record's "ph_hakim2_selesai" value
 * @method string              getPhHakim2Lokasi()         Returns the current record's "ph_hakim2_lokasi" value
 * @method timestamp           getPhPengalihanMulai()      Returns the current record's "ph_pengalihan_mulai" value
 * @method timestamp           getPhPengalihanSelesai()    Returns the current record's "ph_pengalihan_selesai" value
 * @method string              getPhPengalihanLokasi()     Returns the current record's "ph_pengalihan_lokasi" value
 * @method timestamp           getPhPembantaranMulai()     Returns the current record's "ph_pembantaran_mulai" value
 * @method timestamp           getPhPembantaranSelesai()   Returns the current record's "ph_pembantaran_selesai" value
 * @method string              getPhPembantaranLokasi()    Returns the current record's "ph_pembantaran_lokasi" value
 * @method integer             getJenisPutusan()           Returns the current record's "jenis_putusan" value
 * @method string              getPjPidanaCoba()           Returns the current record's "pj_pidana_coba" value
 * @method string              getPjMasaCoba()             Returns the current record's "pj_masa_coba" value
 * @method integer             getPjBadanTahun()           Returns the current record's "pj_badan_tahun" value
 * @method integer             getPjBadanBulan()           Returns the current record's "pj_badan_bulan" value
 * @method integer             getPjBadanHari()            Returns the current record's "pj_badan_hari" value
 * @method decimal             getPjDendaRp()              Returns the current record's "pj_denda_rp" value
 * @method integer             getPjSubTahun()             Returns the current record's "pj_sub_tahun" value
 * @method integer             getPjSubBulan()             Returns the current record's "pj_sub_bulan" value
 * @method integer             getPjSubHari()              Returns the current record's "pj_sub_hari" value
 * @method decimal             getPjBiaya()                Returns the current record's "pj_biaya" value
 * @method integer             getKurunganTahun()          Returns the current record's "kurungan_tahun" value
 * @method integer             getKurunganBulan()          Returns the current record's "kurungan_bulan" value
 * @method integer             getKurunganHari()           Returns the current record's "kurungan_hari" value
 * @method decimal             getDenda()                  Returns the current record's "denda" value
 * @method string              getPutusanTambahan()        Returns the current record's "putusan_tambahan" value
 * @method integer             getSikapJaksa()             Returns the current record's "sikap_jaksa" value
 * @method integer             getSikapTerdakwa()          Returns the current record's "sikap_terdakwa" value
 * @method timestamp           getPhPenyidikMulai()        Returns the current record's "ph_penyidik_mulai" value
 * @method timestamp           getPhPenyidikSelesai()      Returns the current record's "ph_penyidik_selesai" value
 * @method string              getPhPenyidikLokasi()       Returns the current record's "ph_penyidik_lokasi" value
 * @method timestamp           getPhKejariMulai()          Returns the current record's "ph_kejari_mulai" value
 * @method timestamp           getPhKejariSelesai()        Returns the current record's "ph_kejari_selesai" value
 * @method string              getPhKejariLokasi()         Returns the current record's "ph_kejari_lokasi" value
 * @method timestamp           getPhPnMulai()              Returns the current record's "ph_pn_mulai" value
 * @method timestamp           getPhPnSelesai()            Returns the current record's "ph_pn_selesai" value
 * @method string              getPhPnLokasi()             Returns the current record's "ph_pn_lokasi" value
 * @method integer             getUmur()                   Returns the current record's "umur" value
 * @method integer             getIdAgama()                Returns the current record's "id_agama" value
 * @method integer             getPendidikan()             Returns the current record's "pendidikan" value
 * @method integer             getPutusanTetap()           Returns the current record's "putusan_tetap" value
 * @method timestamp           getTglEksekusi()            Returns the current record's "tgl_eksekusi" value
 * @method integer             getPutusanUpayaHukum()      Returns the current record's "putusan_upaya_hukum" value
 * @method timestamp           getTglPtsnBndgKsasi()       Returns the current record's "tgl_ptsn_bndg_ksasi" value
 * @method timestamp           getTglPtsnPkGrasi()         Returns the current record's "tgl_ptsn_pk_grasi" value
 * @method timestamp           getTglEksekusiPkGrasi()     Returns the current record's "tgl_eksekusi_pk_grasi" value
 * @method integer             getPjPidanaCobaThn()        Returns the current record's "pj_pidana_coba_thn" value
 * @method integer             getPjPidanaCobaBln()        Returns the current record's "pj_pidana_coba_bln" value
 * @method integer             getPjPidanaCobaHari()       Returns the current record's "pj_pidana_coba_hari" value
 * @method string              getIdoff()                  Returns the current record's "idoff" value
 * @method integer             getRentutJaksajpu()         Returns the current record's "rentut_jaksajpu" value
 * @method integer             getRentutKasipidum()        Returns the current record's "rentut_kasipidum" value
 * @method integer             getRentutKejari()           Returns the current record's "rentut_kejari" value
 * @method integer             getRentutKejati()           Returns the current record's "rentut_kejati" value
 * @method integer             getRentutKejagung()         Returns the current record's "rentut_kejagung" value
 * @method integer             getPdnPengawasan()          Returns the current record's "pdn_pengawasan" value
 * @method MS_AGAMA            getMSAGAMA()                Returns the current record's "MS_AGAMA" value
 * @method PDM_PERKARA         getPDMPERKARA()             Returns the current record's "PDM_PERKARA" value
 * @method MS_PENDIDIKAN       getMSPENDIDIKAN()           Returns the current record's "MS_PENDIDIKAN" value
 * @method MS_JNSKELAMIN       getMSJNSKELAMIN()           Returns the current record's "MS_JNSKELAMIN" value
 * @method Doctrine_Collection getPDMPASAL()               Returns the current record's "PDM_PASAL" collection
 * @method Doctrine_Collection getPDMUPAYABANDING()        Returns the current record's "PDM_UPAYA_BANDING" collection
 * @method Doctrine_Collection getPDMUPAYAGRASI()          Returns the current record's "PDM_UPAYA_GRASI" collection
 * @method Doctrine_Collection getPDMUPAYAKASASI()         Returns the current record's "PDM_UPAYA_KASASI" collection
 * @method Doctrine_Collection getPDMUPAYAPK()             Returns the current record's "PDM_UPAYA_PK" collection
 * @method PDM_TERSANGKA       setId()                     Sets the current record's "id" value
 * @method PDM_TERSANGKA       setNama()                   Sets the current record's "nama" value
 * @method PDM_TERSANGKA       setTempatLahir()            Sets the current record's "tempat_lahir" value
 * @method PDM_TERSANGKA       setTglLahir()               Sets the current record's "tgl_lahir" value
 * @method PDM_TERSANGKA       setJkl()                    Sets the current record's "jkl" value
 * @method PDM_TERSANGKA       setKewarganegaraan()        Sets the current record's "kewarganegaraan" value
 * @method PDM_TERSANGKA       setAlamat()                 Sets the current record's "alamat" value
 * @method PDM_TERSANGKA       setPekerjaan()              Sets the current record's "pekerjaan" value
 * @method PDM_TERSANGKA       setIdPerkara()              Sets the current record's "id_perkara" value
 * @method PDM_TERSANGKA       setPhJpuMulai()             Sets the current record's "ph_jpu_mulai" value
 * @method PDM_TERSANGKA       setPhJpuSelesai()           Sets the current record's "ph_jpu_selesai" value
 * @method PDM_TERSANGKA       setPhJpuLokasi()            Sets the current record's "ph_jpu_lokasi" value
 * @method PDM_TERSANGKA       setPhHakim1Mulai()          Sets the current record's "ph_hakim1_mulai" value
 * @method PDM_TERSANGKA       setPhHakim1Selesai()        Sets the current record's "ph_hakim1_selesai" value
 * @method PDM_TERSANGKA       setPhHakim1Lokasi()         Sets the current record's "ph_hakim1_lokasi" value
 * @method PDM_TERSANGKA       setPhHakim2Mulai()          Sets the current record's "ph_hakim2_mulai" value
 * @method PDM_TERSANGKA       setPhHakim2Selesai()        Sets the current record's "ph_hakim2_selesai" value
 * @method PDM_TERSANGKA       setPhHakim2Lokasi()         Sets the current record's "ph_hakim2_lokasi" value
 * @method PDM_TERSANGKA       setPhPengalihanMulai()      Sets the current record's "ph_pengalihan_mulai" value
 * @method PDM_TERSANGKA       setPhPengalihanSelesai()    Sets the current record's "ph_pengalihan_selesai" value
 * @method PDM_TERSANGKA       setPhPengalihanLokasi()     Sets the current record's "ph_pengalihan_lokasi" value
 * @method PDM_TERSANGKA       setPhPembantaranMulai()     Sets the current record's "ph_pembantaran_mulai" value
 * @method PDM_TERSANGKA       setPhPembantaranSelesai()   Sets the current record's "ph_pembantaran_selesai" value
 * @method PDM_TERSANGKA       setPhPembantaranLokasi()    Sets the current record's "ph_pembantaran_lokasi" value
 * @method PDM_TERSANGKA       setJenisPutusan()           Sets the current record's "jenis_putusan" value
 * @method PDM_TERSANGKA       setPjPidanaCoba()           Sets the current record's "pj_pidana_coba" value
 * @method PDM_TERSANGKA       setPjMasaCoba()             Sets the current record's "pj_masa_coba" value
 * @method PDM_TERSANGKA       setPjBadanTahun()           Sets the current record's "pj_badan_tahun" value
 * @method PDM_TERSANGKA       setPjBadanBulan()           Sets the current record's "pj_badan_bulan" value
 * @method PDM_TERSANGKA       setPjBadanHari()            Sets the current record's "pj_badan_hari" value
 * @method PDM_TERSANGKA       setPjDendaRp()              Sets the current record's "pj_denda_rp" value
 * @method PDM_TERSANGKA       setPjSubTahun()             Sets the current record's "pj_sub_tahun" value
 * @method PDM_TERSANGKA       setPjSubBulan()             Sets the current record's "pj_sub_bulan" value
 * @method PDM_TERSANGKA       setPjSubHari()              Sets the current record's "pj_sub_hari" value
 * @method PDM_TERSANGKA       setPjBiaya()                Sets the current record's "pj_biaya" value
 * @method PDM_TERSANGKA       setKurunganTahun()          Sets the current record's "kurungan_tahun" value
 * @method PDM_TERSANGKA       setKurunganBulan()          Sets the current record's "kurungan_bulan" value
 * @method PDM_TERSANGKA       setKurunganHari()           Sets the current record's "kurungan_hari" value
 * @method PDM_TERSANGKA       setDenda()                  Sets the current record's "denda" value
 * @method PDM_TERSANGKA       setPutusanTambahan()        Sets the current record's "putusan_tambahan" value
 * @method PDM_TERSANGKA       setSikapJaksa()             Sets the current record's "sikap_jaksa" value
 * @method PDM_TERSANGKA       setSikapTerdakwa()          Sets the current record's "sikap_terdakwa" value
 * @method PDM_TERSANGKA       setPhPenyidikMulai()        Sets the current record's "ph_penyidik_mulai" value
 * @method PDM_TERSANGKA       setPhPenyidikSelesai()      Sets the current record's "ph_penyidik_selesai" value
 * @method PDM_TERSANGKA       setPhPenyidikLokasi()       Sets the current record's "ph_penyidik_lokasi" value
 * @method PDM_TERSANGKA       setPhKejariMulai()          Sets the current record's "ph_kejari_mulai" value
 * @method PDM_TERSANGKA       setPhKejariSelesai()        Sets the current record's "ph_kejari_selesai" value
 * @method PDM_TERSANGKA       setPhKejariLokasi()         Sets the current record's "ph_kejari_lokasi" value
 * @method PDM_TERSANGKA       setPhPnMulai()              Sets the current record's "ph_pn_mulai" value
 * @method PDM_TERSANGKA       setPhPnSelesai()            Sets the current record's "ph_pn_selesai" value
 * @method PDM_TERSANGKA       setPhPnLokasi()             Sets the current record's "ph_pn_lokasi" value
 * @method PDM_TERSANGKA       setUmur()                   Sets the current record's "umur" value
 * @method PDM_TERSANGKA       setIdAgama()                Sets the current record's "id_agama" value
 * @method PDM_TERSANGKA       setPendidikan()             Sets the current record's "pendidikan" value
 * @method PDM_TERSANGKA       setPutusanTetap()           Sets the current record's "putusan_tetap" value
 * @method PDM_TERSANGKA       setTglEksekusi()            Sets the current record's "tgl_eksekusi" value
 * @method PDM_TERSANGKA       setPutusanUpayaHukum()      Sets the current record's "putusan_upaya_hukum" value
 * @method PDM_TERSANGKA       setTglPtsnBndgKsasi()       Sets the current record's "tgl_ptsn_bndg_ksasi" value
 * @method PDM_TERSANGKA       setTglPtsnPkGrasi()         Sets the current record's "tgl_ptsn_pk_grasi" value
 * @method PDM_TERSANGKA       setTglEksekusiPkGrasi()     Sets the current record's "tgl_eksekusi_pk_grasi" value
 * @method PDM_TERSANGKA       setPjPidanaCobaThn()        Sets the current record's "pj_pidana_coba_thn" value
 * @method PDM_TERSANGKA       setPjPidanaCobaBln()        Sets the current record's "pj_pidana_coba_bln" value
 * @method PDM_TERSANGKA       setPjPidanaCobaHari()       Sets the current record's "pj_pidana_coba_hari" value
 * @method PDM_TERSANGKA       setIdoff()                  Sets the current record's "idoff" value
 * @method PDM_TERSANGKA       setRentutJaksajpu()         Sets the current record's "rentut_jaksajpu" value
 * @method PDM_TERSANGKA       setRentutKasipidum()        Sets the current record's "rentut_kasipidum" value
 * @method PDM_TERSANGKA       setRentutKejari()           Sets the current record's "rentut_kejari" value
 * @method PDM_TERSANGKA       setRentutKejati()           Sets the current record's "rentut_kejati" value
 * @method PDM_TERSANGKA       setRentutKejagung()         Sets the current record's "rentut_kejagung" value
 * @method PDM_TERSANGKA       setPdnPengawasan()          Sets the current record's "pdn_pengawasan" value
 * @method PDM_TERSANGKA       setMSAGAMA()                Sets the current record's "MS_AGAMA" value
 * @method PDM_TERSANGKA       setPDMPERKARA()             Sets the current record's "PDM_PERKARA" value
 * @method PDM_TERSANGKA       setMSPENDIDIKAN()           Sets the current record's "MS_PENDIDIKAN" value
 * @method PDM_TERSANGKA       setMSJNSKELAMIN()           Sets the current record's "MS_JNSKELAMIN" value
 * @method PDM_TERSANGKA       setPDMPASAL()               Sets the current record's "PDM_PASAL" collection
 * @method PDM_TERSANGKA       setPDMUPAYABANDING()        Sets the current record's "PDM_UPAYA_BANDING" collection
 * @method PDM_TERSANGKA       setPDMUPAYAGRASI()          Sets the current record's "PDM_UPAYA_GRASI" collection
 * @method PDM_TERSANGKA       setPDMUPAYAKASASI()         Sets the current record's "PDM_UPAYA_KASASI" collection
 * @method PDM_TERSANGKA       setPDMUPAYAPK()             Sets the current record's "PDM_UPAYA_PK" collection
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDM_TERSANGKA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDM_TERSANGKA');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
			 'sequence' => 'PDM_TERSANGKA',
             'length' => 8,
             ));
        $this->hasColumn('nama', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('tempat_lahir', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('tgl_lahir', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('jkl', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('kewarganegaraan', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('alamat', 'string', 200, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 200,
             ));
        $this->hasColumn('pekerjaan', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('id_perkara', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('ph_jpu_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_jpu_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_jpu_lokasi', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('ph_hakim1_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_hakim1_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_hakim1_lokasi', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('ph_hakim2_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_hakim2_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_hakim2_lokasi', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('ph_pengalihan_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pengalihan_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pengalihan_lokasi', 'string', 30, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('ph_pembantaran_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pembantaran_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pembantaran_lokasi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('jenis_putusan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('pj_pidana_coba', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('pj_masa_coba', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('denda', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('sikap_jaksa', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('sikap_terdakwa', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('ph_penyidik_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_penyidik_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_penyidik_lokasi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ph_kejari_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_kejari_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_kejari_lokasi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('ph_pn_mulai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pn_selesai', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('ph_pn_lokasi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('umur', 'integer', 3, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 3,
             ));
        $this->hasColumn('id_agama', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pendidikan', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('putusan_tetap', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('tgl_eksekusi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('putusan_upaya_hukum', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('tgl_ptsn_bndg_ksasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_ptsn_pk_grasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_eksekusi_pk_grasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('idoff', 'string', 25, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('rentut_jaksajpu', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('rentut_kasipidum', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('rentut_kejari', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('rentut_kejati', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('rentut_kejagung', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('pdn_pengawasan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MS_AGAMA', array(
             'local' => 'id_agama',
             'foreign' => 'id'));

        $this->hasOne('PDM_PERKARA', array(
             'local' => 'id_perkara',
             'foreign' => 'id'));

        $this->hasOne('MS_PENDIDIKAN', array(
             'local' => 'pendidikan',
             'foreign' => 'id'));

        $this->hasOne('MS_JNSKELAMIN', array(
             'local' => 'jkl',
             'foreign' => 'id'));

        $this->hasMany('PDM_PASAL', array(
             'local' => 'id',
             'foreign' => 'id_tersangka'));

        $this->hasMany('PDM_UPAYA_BANDING', array(
             'local' => 'id',
             'foreign' => 'id_tersangka'));

        $this->hasMany('PDM_UPAYA_GRASI', array(
             'local' => 'id',
             'foreign' => 'id_tersangka'));

        $this->hasMany('PDM_UPAYA_KASASI', array(
             'local' => 'id',
             'foreign' => 'id_tersangka'));

        $this->hasMany('PDM_UPAYA_PK', array(
             'local' => 'id',
             'foreign' => 'id_tersangka'));
    }
}