<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_UPAYA_PK', 'doctrine');

/**
 * BasePDS_UPAYA_PK
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $no_pk
 * @property timestamp $tgl_pk
 * @property timestamp $tgl_nota_pk
 * @property string $isi_nota_pk
 * @property string $no_putusan
 * @property timestamp $tgl_putusan
 * @property string $isi_putusan
 * @property integer $id_tersangka
 * @property integer $jenis_putusan
 * @property integer $pj_badan_tahun
 * @property integer $pj_badan_bulan
 * @property integer $pj_badan_hari
 * @property integer $kurungan_tahun
 * @property integer $kurungan_bulan
 * @property integer $kurungan_hari
 * @property integer $denda
 * @property decimal $pj_denda_rp
 * @property integer $pj_sub_tahun
 * @property integer $pj_sub_bulan
 * @property integer $pj_sub_hari
 * @property integer $pj_pidana_coba_thn
 * @property integer $pj_pidana_coba_bln
 * @property integer $pj_pidana_coba_hari
 * @property string $putusan_tambahan
 * @property integer $uang_pengganti
 * @property integer $uang_pengganti_lain
 * @property integer $mata_uang_lain
 * @property integer $sub_pengganti_tahun
 * @property integer $sub_pengganti_bulan
 * @property integer $sub_pengganti_hari
 * @property decimal $pj_biaya
 * @property integer $sikap_terdakwa
 * @property integer $jns_pk
 * @property PDS_TERSANGKA $PDS_TERSANGKA
 * 
 * @method integer       getId()                  Returns the current record's "id" value
 * @method string        getNoPk()                Returns the current record's "no_pk" value
 * @method timestamp     getTglPk()               Returns the current record's "tgl_pk" value
 * @method timestamp     getTglNotaPk()           Returns the current record's "tgl_nota_pk" value
 * @method string        getIsiNotaPk()           Returns the current record's "isi_nota_pk" value
 * @method string        getNoPutusan()           Returns the current record's "no_putusan" value
 * @method timestamp     getTglPutusan()          Returns the current record's "tgl_putusan" value
 * @method string        getIsiPutusan()          Returns the current record's "isi_putusan" value
 * @method integer       getIdTersangka()         Returns the current record's "id_tersangka" value
 * @method integer       getJenisPutusan()        Returns the current record's "jenis_putusan" value
 * @method integer       getPjBadanTahun()        Returns the current record's "pj_badan_tahun" value
 * @method integer       getPjBadanBulan()        Returns the current record's "pj_badan_bulan" value
 * @method integer       getPjBadanHari()         Returns the current record's "pj_badan_hari" value
 * @method integer       getKurunganTahun()       Returns the current record's "kurungan_tahun" value
 * @method integer       getKurunganBulan()       Returns the current record's "kurungan_bulan" value
 * @method integer       getKurunganHari()        Returns the current record's "kurungan_hari" value
 * @method integer       getDenda()               Returns the current record's "denda" value
 * @method decimal       getPjDendaRp()           Returns the current record's "pj_denda_rp" value
 * @method integer       getPjSubTahun()          Returns the current record's "pj_sub_tahun" value
 * @method integer       getPjSubBulan()          Returns the current record's "pj_sub_bulan" value
 * @method integer       getPjSubHari()           Returns the current record's "pj_sub_hari" value
 * @method integer       getPjPidanaCobaThn()     Returns the current record's "pj_pidana_coba_thn" value
 * @method integer       getPjPidanaCobaBln()     Returns the current record's "pj_pidana_coba_bln" value
 * @method integer       getPjPidanaCobaHari()    Returns the current record's "pj_pidana_coba_hari" value
 * @method string        getPutusanTambahan()     Returns the current record's "putusan_tambahan" value
 * @method integer       getUangPengganti()       Returns the current record's "uang_pengganti" value
 * @method integer       getUangPenggantiLain()   Returns the current record's "uang_pengganti_lain" value
 * @method integer       getMataUangLain()        Returns the current record's "mata_uang_lain" value
 * @method integer       getSubPenggantiTahun()   Returns the current record's "sub_pengganti_tahun" value
 * @method integer       getSubPenggantiBulan()   Returns the current record's "sub_pengganti_bulan" value
 * @method integer       getSubPenggantiHari()    Returns the current record's "sub_pengganti_hari" value
 * @method decimal       getPjBiaya()             Returns the current record's "pj_biaya" value
 * @method integer       getSikapTerdakwa()       Returns the current record's "sikap_terdakwa" value
 * @method integer       getJnsPk()               Returns the current record's "jns_pk" value
 * @method PDS_TERSANGKA getPDSTERSANGKA()        Returns the current record's "PDS_TERSANGKA" value
 * @method PDS_UPAYA_PK  setId()                  Sets the current record's "id" value
 * @method PDS_UPAYA_PK  setNoPk()                Sets the current record's "no_pk" value
 * @method PDS_UPAYA_PK  setTglPk()               Sets the current record's "tgl_pk" value
 * @method PDS_UPAYA_PK  setTglNotaPk()           Sets the current record's "tgl_nota_pk" value
 * @method PDS_UPAYA_PK  setIsiNotaPk()           Sets the current record's "isi_nota_pk" value
 * @method PDS_UPAYA_PK  setNoPutusan()           Sets the current record's "no_putusan" value
 * @method PDS_UPAYA_PK  setTglPutusan()          Sets the current record's "tgl_putusan" value
 * @method PDS_UPAYA_PK  setIsiPutusan()          Sets the current record's "isi_putusan" value
 * @method PDS_UPAYA_PK  setIdTersangka()         Sets the current record's "id_tersangka" value
 * @method PDS_UPAYA_PK  setJenisPutusan()        Sets the current record's "jenis_putusan" value
 * @method PDS_UPAYA_PK  setPjBadanTahun()        Sets the current record's "pj_badan_tahun" value
 * @method PDS_UPAYA_PK  setPjBadanBulan()        Sets the current record's "pj_badan_bulan" value
 * @method PDS_UPAYA_PK  setPjBadanHari()         Sets the current record's "pj_badan_hari" value
 * @method PDS_UPAYA_PK  setKurunganTahun()       Sets the current record's "kurungan_tahun" value
 * @method PDS_UPAYA_PK  setKurunganBulan()       Sets the current record's "kurungan_bulan" value
 * @method PDS_UPAYA_PK  setKurunganHari()        Sets the current record's "kurungan_hari" value
 * @method PDS_UPAYA_PK  setDenda()               Sets the current record's "denda" value
 * @method PDS_UPAYA_PK  setPjDendaRp()           Sets the current record's "pj_denda_rp" value
 * @method PDS_UPAYA_PK  setPjSubTahun()          Sets the current record's "pj_sub_tahun" value
 * @method PDS_UPAYA_PK  setPjSubBulan()          Sets the current record's "pj_sub_bulan" value
 * @method PDS_UPAYA_PK  setPjSubHari()           Sets the current record's "pj_sub_hari" value
 * @method PDS_UPAYA_PK  setPjPidanaCobaThn()     Sets the current record's "pj_pidana_coba_thn" value
 * @method PDS_UPAYA_PK  setPjPidanaCobaBln()     Sets the current record's "pj_pidana_coba_bln" value
 * @method PDS_UPAYA_PK  setPjPidanaCobaHari()    Sets the current record's "pj_pidana_coba_hari" value
 * @method PDS_UPAYA_PK  setPutusanTambahan()     Sets the current record's "putusan_tambahan" value
 * @method PDS_UPAYA_PK  setUangPengganti()       Sets the current record's "uang_pengganti" value
 * @method PDS_UPAYA_PK  setUangPenggantiLain()   Sets the current record's "uang_pengganti_lain" value
 * @method PDS_UPAYA_PK  setMataUangLain()        Sets the current record's "mata_uang_lain" value
 * @method PDS_UPAYA_PK  setSubPenggantiTahun()   Sets the current record's "sub_pengganti_tahun" value
 * @method PDS_UPAYA_PK  setSubPenggantiBulan()   Sets the current record's "sub_pengganti_bulan" value
 * @method PDS_UPAYA_PK  setSubPenggantiHari()    Sets the current record's "sub_pengganti_hari" value
 * @method PDS_UPAYA_PK  setPjBiaya()             Sets the current record's "pj_biaya" value
 * @method PDS_UPAYA_PK  setSikapTerdakwa()       Sets the current record's "sikap_terdakwa" value
 * @method PDS_UPAYA_PK  setJnsPk()               Sets the current record's "jns_pk" value
 * @method PDS_UPAYA_PK  setPDSTERSANGKA()        Sets the current record's "PDS_TERSANGKA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_UPAYA_PK extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_UPAYA_PK');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('no_pk', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_pk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('tgl_nota_pk', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_nota_pk', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('no_putusan', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_putusan', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_putusan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('jenis_putusan', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('pj_badan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_badan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_badan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('kurungan_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('kurungan_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('kurungan_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('denda', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('pj_denda_rp', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('pj_sub_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_sub_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_sub_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_pidana_coba_thn', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pj_pidana_coba_bln', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_pidana_coba_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('putusan_tambahan', 'string', 1000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1000,
             ));
        $this->hasColumn('uang_pengganti', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('uang_pengganti_lain', 'integer', 16, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('mata_uang_lain', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('sub_pengganti_tahun', 'integer', 4, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('sub_pengganti_bulan', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('sub_pengganti_hari', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('pj_biaya', 'decimal', 16, array(
             'notnull' => false,
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 16,
             ));
        $this->hasColumn('sikap_terdakwa', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('jns_pk', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_TERSANGKA', array(
             'local' => 'id_tersangka',
             'foreign' => 'id'));
    }
}