<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDS_PASAL_BANDING', 'doctrine');

/**
 * BasePDS_PASAL_BANDING
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_banding
 * @property string $pasal
 * @property integer $terbukti
 * @property PDS_UPAYA_BANDING $PDS_UPAYA_BANDING
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method integer           getIdBanding()         Returns the current record's "id_banding" value
 * @method string            getPasal()             Returns the current record's "pasal" value
 * @method integer           getTerbukti()          Returns the current record's "terbukti" value
 * @method PDS_UPAYA_BANDING getPDSUPAYABANDING()   Returns the current record's "PDS_UPAYA_BANDING" value
 * @method PDS_PASAL_BANDING setId()                Sets the current record's "id" value
 * @method PDS_PASAL_BANDING setIdBanding()         Sets the current record's "id_banding" value
 * @method PDS_PASAL_BANDING setPasal()             Sets the current record's "pasal" value
 * @method PDS_PASAL_BANDING setTerbukti()          Sets the current record's "terbukti" value
 * @method PDS_PASAL_BANDING setPDSUPAYABANDING()   Sets the current record's "PDS_UPAYA_BANDING" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDS_PASAL_BANDING extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDS_PASAL_BANDING');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_banding', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('pasal', 'string', 500, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 500,
             ));
        $this->hasColumn('terbukti', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDS_UPAYA_BANDING', array(
             'local' => 'id_banding',
             'foreign' => 'id'));
    }
}