<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDM_PASAL_KASASI', 'doctrine');

/**
 * BasePDM_PASAL_KASASI
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_kasasi
 * @property string $pasal
 * @property integer $terbukti
 * @property string $idoff
 * @property PDM_UPAYA_KASASI $PDM_UPAYA_KASASI
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getIdKasasi()         Returns the current record's "id_kasasi" value
 * @method string           getPasal()            Returns the current record's "pasal" value
 * @method integer          getTerbukti()         Returns the current record's "terbukti" value
 * @method string           getIdoff()            Returns the current record's "idoff" value
 * @method PDM_UPAYA_KASASI getPDMUPAYAKASASI()   Returns the current record's "PDM_UPAYA_KASASI" value
 * @method PDM_PASAL_KASASI setId()               Sets the current record's "id" value
 * @method PDM_PASAL_KASASI setIdKasasi()         Sets the current record's "id_kasasi" value
 * @method PDM_PASAL_KASASI setPasal()            Sets the current record's "pasal" value
 * @method PDM_PASAL_KASASI setTerbukti()         Sets the current record's "terbukti" value
 * @method PDM_PASAL_KASASI setIdoff()            Sets the current record's "idoff" value
 * @method PDM_PASAL_KASASI setPDMUPAYAKASASI()   Sets the current record's "PDM_UPAYA_KASASI" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDM_PASAL_KASASI extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDM_PASAL_KASASI');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_kasasi', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('pasal', 'string', 500, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 500,
             ));
        $this->hasColumn('terbukti', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('idoff', 'string', 25, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDM_UPAYA_KASASI', array(
             'local' => 'id_kasasi',
             'foreign' => 'id'));
    }
}