<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PDM_UPAYA_GRASI', 'doctrine');

/**
 * BasePDM_UPAYA_GRASI
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $no_grasi
 * @property timestamp $tgl_grasi
 * @property string $no_keppres
 * @property timestamp $tgl_keppres
 * @property string $isi_keppres
 * @property integer $id_tersangka
 * @property timestamp $tgl_timbang_grasi
 * @property string $isi_timbang_grasi
 * @property string $idoff
 * @property PDM_TERSANGKA $PDM_TERSANGKA
 * 
 * @method integer         getId()                Returns the current record's "id" value
 * @method string          getNoGrasi()           Returns the current record's "no_grasi" value
 * @method timestamp       getTglGrasi()          Returns the current record's "tgl_grasi" value
 * @method string          getNoKeppres()         Returns the current record's "no_keppres" value
 * @method timestamp       getTglKeppres()        Returns the current record's "tgl_keppres" value
 * @method string          getIsiKeppres()        Returns the current record's "isi_keppres" value
 * @method integer         getIdTersangka()       Returns the current record's "id_tersangka" value
 * @method timestamp       getTglTimbangGrasi()   Returns the current record's "tgl_timbang_grasi" value
 * @method string          getIsiTimbangGrasi()   Returns the current record's "isi_timbang_grasi" value
 * @method string          getIdoff()             Returns the current record's "idoff" value
 * @method PDM_TERSANGKA   getPDMTERSANGKA()      Returns the current record's "PDM_TERSANGKA" value
 * @method PDM_UPAYA_GRASI setId()                Sets the current record's "id" value
 * @method PDM_UPAYA_GRASI setNoGrasi()           Sets the current record's "no_grasi" value
 * @method PDM_UPAYA_GRASI setTglGrasi()          Sets the current record's "tgl_grasi" value
 * @method PDM_UPAYA_GRASI setNoKeppres()         Sets the current record's "no_keppres" value
 * @method PDM_UPAYA_GRASI setTglKeppres()        Sets the current record's "tgl_keppres" value
 * @method PDM_UPAYA_GRASI setIsiKeppres()        Sets the current record's "isi_keppres" value
 * @method PDM_UPAYA_GRASI setIdTersangka()       Sets the current record's "id_tersangka" value
 * @method PDM_UPAYA_GRASI setTglTimbangGrasi()   Sets the current record's "tgl_timbang_grasi" value
 * @method PDM_UPAYA_GRASI setIsiTimbangGrasi()   Sets the current record's "isi_timbang_grasi" value
 * @method PDM_UPAYA_GRASI setIdoff()             Sets the current record's "idoff" value
 * @method PDM_UPAYA_GRASI setPDMTERSANGKA()      Sets the current record's "PDM_TERSANGKA" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePDM_UPAYA_GRASI extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PDM_UPAYA_GRASI');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('no_grasi', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_grasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('no_keppres', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('tgl_keppres', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_keppres', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('id_tersangka', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('tgl_timbang_grasi', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('isi_timbang_grasi', 'string', 4000, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 4000,
             ));
        $this->hasColumn('idoff', 'string', 25, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PDM_TERSANGKA', array(
             'local' => 'id_tersangka',
             'foreign' => 'id'));
    }
}