<?php

/**
 * DTN_PUP_PDS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DTN_PUP_PDS extends BaseDTN_PUP_PDS
{
}
