<?php

/**
 * PDS_SATUAN_REF
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PDS_SATUAN_REF extends BasePDS_SATUAN_REF
{
}
