<?php

/**
 * PDM_PERKARA form base class.
 *
 * @method PDM_PERKARA getObject() Returns the current form's model object
 *
 * @package    dnt
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 24171 2009-11-19 16:37:50Z Kris.Wallsmith $
 */
abstract class BasePDM_PERKARAForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                     => new sfWidgetFormInputHidden(),
      'nomor_perkara'          => new sfWidgetFormInputText(),
      'posisi_kasus'           => new sfWidgetFormTextarea(),
      'id_pk_ting'             => new sfWidgetFormInputText(),
      'penyidik'               => new sfWidgetFormInputText(),
      'no_spdp'                => new sfWidgetFormInputText(),
      'tgl_spdp'               => new sfWidgetFormDateTime(),
      'penerima'               => new sfWidgetFormInputText(),
      'tgl_diterima'           => new sfWidgetFormDateTime(),
      'no_p16'                 => new sfWidgetFormInputText(),
      'tgl_p16'                => new sfWidgetFormDateTime(),
      'tgl_konsultasi'         => new sfWidgetFormDateTime(),
      'isi_konsultasi'         => new sfWidgetFormTextarea(),
      'no_p17'                 => new sfWidgetFormInputText(),
      'tgl_p17'                => new sfWidgetFormDateTime(),
      'no_kirim_berkas'        => new sfWidgetFormInputText(),
      'tgl_kirim_berkas'       => new sfWidgetFormDateTime(),
      'no_p21'                 => new sfWidgetFormInputText(),
      'tgl_p21'                => new sfWidgetFormDateTime(),
      'no_p21a'                => new sfWidgetFormInputText(),
      'tgl_p21a'               => new sfWidgetFormDateTime(),
      'no_kembali_berkas'      => new sfWidgetFormInputText(),
      'tgl_kembali_berkas'     => new sfWidgetFormDateTime(),
      'kd_penyelesaian'        => new sfWidgetFormInputText(),
      'id_instansi'            => new sfWidgetFormInputText(),
      'no_p16a'                => new sfWidgetFormInputText(),
      'tgl_p16a'               => new sfWidgetFormDateTime(),
      'tgl_terima_tsk'         => new sfWidgetFormDateTime(),
      'no_henti_tut'           => new sfWidgetFormInputText(),
      'tgl_henti_tut'          => new sfWidgetFormDateTime(),
      'pertimbangan_henti'     => new sfWidgetFormTextarea(),
      'no_limpah_pk'           => new sfWidgetFormInputText(),
      'tgl_diterima_pn'        => new sfWidgetFormDateTime(),
      'tgl_tap_sidang'         => new sfWidgetFormDateTime(),
      'tgl_baca_dakwaan'       => new sfWidgetFormDateTime(),
      'isi_dakwaan'            => new sfWidgetFormTextarea(),
      'tgl_awal_bukti'         => new sfWidgetFormDateTime(),
      'tgl_akhir_bukti'        => new sfWidgetFormDateTime(),
      'tgl_juk_kajari'         => new sfWidgetFormDateTime(),
      'isi_juk_kajari'         => new sfWidgetFormTextarea(),
      'no_usul_kajari'         => new sfWidgetFormInputText(),
      'tgl_usul_kajari'        => new sfWidgetFormDateTime(),
      'tgl_juk_kajati'         => new sfWidgetFormDateTime(),
      'isi_juk_kajati'         => new sfWidgetFormTextarea(),
      'no_usul_kajati'         => new sfWidgetFormInputText(),
      'tgl_usul_kajati'        => new sfWidgetFormDateTime(),
      'tgl_juk_ja'             => new sfWidgetFormDateTime(),
      'isi_juk_ja'             => new sfWidgetFormTextarea(),
      'no_usul_ja'             => new sfWidgetFormInputText(),
      'tgl_usul_ja'            => new sfWidgetFormDateTime(),
      'tgl_baca_tut'           => new sfWidgetFormDateTime(),
      'isi_tuntutan'           => new sfWidgetFormTextarea(),
      'tgl_putusan_pn'         => new sfWidgetFormDateTime(),
      'tgl_terima_putusan'     => new sfWidgetFormDateTime(),
      'kd_putusan_hukum'       => new sfWidgetFormInputText(),
      'tgl_putusan_hukum'      => new sfWidgetFormDateTime(),
      'no_barbuk'              => new sfWidgetFormInputText(),
      'tgl_barbuk'             => new sfWidgetFormDateTime(),
      'no_konsultasi'          => new sfWidgetFormInputText(),
      'no_p20'                 => new sfWidgetFormInputText(),
      'tgl_p20'                => new sfWidgetFormDateTime(),
      'no_optimal'             => new sfWidgetFormInputText(),
      'tgl_optimal'            => new sfWidgetFormDateTime(),
      'isi_pemeriksaan'        => new sfWidgetFormTextarea(),
      'tgl_limpah_pk'          => new sfWidgetFormDateTime(),
      'created_by'             => new sfWidgetFormInputText(),
      'created_time'           => new sfWidgetFormDateTime(),
      'created_ip'             => new sfWidgetFormInputText(),
      'lastupdate_by'          => new sfWidgetFormInputText(),
      'lastupdate_time'        => new sfWidgetFormDateTime(),
      'lastupdate_ip'          => new sfWidgetFormInputText(),
      'inst_satkerkd'          => new sfWidgetFormInputText(),
      'terdakwa'               => new sfWidgetFormTextarea(),
      'jaksa_penuntut_umum'    => new sfWidgetFormTextarea(),
      'id_perkara'             => new sfWidgetFormInputText(),
      'pasal_yg_ddkwkn'        => new sfWidgetFormTextarea(),
      'pasal_yg_dilanggar'     => new sfWidgetFormInputText(),
      'p16_tim'                => new sfWidgetFormTextarea(),
      'dtl_dakwaan'            => new sfWidgetFormTextarea(),
      'tuntutan'               => new sfWidgetFormTextarea(),
      'amar_tuntutan'          => new sfWidgetFormTextarea(),
      'status'                 => new sfWidgetFormInputText(),
      'p16a_tim'               => new sfWidgetFormTextarea(),
      'ditahan_jpu_awal'       => new sfWidgetFormDateTime(),
      'ditahan_jpu_akhir'      => new sfWidgetFormDateTime(),
      'ditahan_jpu_tmpt'       => new sfWidgetFormInputText(),
      'dprjng_hkm_kt_pn_awal'  => new sfWidgetFormDateTime(),
      'dprjng_hkm_kt_pn_akhir' => new sfWidgetFormDateTime(),
      'dprjng_hkm_kt_pn_tmpt'  => new sfWidgetFormInputText(),
      'pengalihan_tahan_awal'  => new sfWidgetFormDateTime(),
      'pengalihan_tahan_akh'   => new sfWidgetFormDateTime(),
      'pengalihan_tahan_tmpt'  => new sfWidgetFormInputText(),
      'pmbtr_sjk_awal'         => new sfWidgetFormDateTime(),
      'pmbtr_sjk_akhir'        => new sfWidgetFormDateTime(),
      'pmbtr_dtl'              => new sfWidgetFormInputText(),
      'tgl_putusan_hkm_tetap'  => new sfWidgetFormDateTime(),
      'tgl_grasi'              => new sfWidgetFormDateTime(),
      'tgl_pk'                 => new sfWidgetFormDateTime(),
      'tgl_akta_kasasi'        => new sfWidgetFormDateTime(),
      'tgl_akta_banding'       => new sfWidgetFormDateTime(),
      'p16a_tgl'               => new sfWidgetFormDateTime(),
      'p16_tgl'                => new sfWidgetFormDateTime(),
      'idoff'                  => new sfWidgetFormInputText(),
      'tgl_tuntut_jpu'         => new sfWidgetFormDateTime(),
      'isi_rentut_jpu'         => new sfWidgetFormTextarea(),
      'isi_pendapat_kasi'      => new sfWidgetFormTextarea(),
      'tgl_pendapat_kasi'      => new sfWidgetFormDateTime(),
      'nama_berkas_dakwaan'    => new sfWidgetFormInputText(),
      'idasalperkara'          => new sfWidgetFormInputText(),
      'idpenyelesaian'         => new sfWidgetFormInputText(),
      'no_lanjut_pratut'       => new sfWidgetFormInputText(),
      'tgl_lanjut_pratut'      => new sfWidgetFormDateTime(),
      'no_henti_pratut'        => new sfWidgetFormInputText(),
      'tgl_henti_pratut'       => new sfWidgetFormDateTime(),
      'no_optimal_pratut'      => new sfWidgetFormInputText(),
      'tgl_optimal_pratut'     => new sfWidgetFormDateTime(),
    ));

    $this->setValidators(array(
      'id'                     => new sfValidatorDoctrineChoice(array('model' => $this->getModelName(), 'column' => 'id', 'required' => false)),
      'nomor_perkara'          => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'posisi_kasus'           => new sfValidatorString(array('required' => false)),
      'id_pk_ting'             => new sfValidatorInteger(array('required' => false)),
      'penyidik'               => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'no_spdp'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_spdp'               => new sfValidatorDateTime(array('required' => false)),
      'penerima'               => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_diterima'           => new sfValidatorDateTime(array('required' => false)),
      'no_p16'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p16'                => new sfValidatorDateTime(array('required' => false)),
      'tgl_konsultasi'         => new sfValidatorDateTime(array('required' => false)),
      'isi_konsultasi'         => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'no_p17'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p17'                => new sfValidatorDateTime(array('required' => false)),
      'no_kirim_berkas'        => new sfValidatorString(array('max_length' => 225, 'required' => false)),
      'tgl_kirim_berkas'       => new sfValidatorDateTime(array('required' => false)),
      'no_p21'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p21'                => new sfValidatorDateTime(array('required' => false)),
      'no_p21a'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p21a'               => new sfValidatorDateTime(array('required' => false)),
      'no_kembali_berkas'      => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_kembali_berkas'     => new sfValidatorDateTime(array('required' => false)),
      'kd_penyelesaian'        => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'id_instansi'            => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'no_p16a'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p16a'               => new sfValidatorDateTime(array('required' => false)),
      'tgl_terima_tsk'         => new sfValidatorDateTime(array('required' => false)),
      'no_henti_tut'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_henti_tut'          => new sfValidatorDateTime(array('required' => false)),
      'pertimbangan_henti'     => new sfValidatorString(array('required' => false)),
      'no_limpah_pk'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_diterima_pn'        => new sfValidatorDateTime(array('required' => false)),
      'tgl_tap_sidang'         => new sfValidatorDateTime(array('required' => false)),
      'tgl_baca_dakwaan'       => new sfValidatorDateTime(array('required' => false)),
      'isi_dakwaan'            => new sfValidatorString(array('required' => false)),
      'tgl_awal_bukti'         => new sfValidatorDateTime(array('required' => false)),
      'tgl_akhir_bukti'        => new sfValidatorDateTime(array('required' => false)),
      'tgl_juk_kajari'         => new sfValidatorDateTime(array('required' => false)),
      'isi_juk_kajari'         => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'no_usul_kajari'         => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_usul_kajari'        => new sfValidatorDateTime(array('required' => false)),
      'tgl_juk_kajati'         => new sfValidatorDateTime(array('required' => false)),
      'isi_juk_kajati'         => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'no_usul_kajati'         => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_usul_kajati'        => new sfValidatorDateTime(array('required' => false)),
      'tgl_juk_ja'             => new sfValidatorDateTime(array('required' => false)),
      'isi_juk_ja'             => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'no_usul_ja'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_usul_ja'            => new sfValidatorDateTime(array('required' => false)),
      'tgl_baca_tut'           => new sfValidatorDateTime(array('required' => false)),
      'isi_tuntutan'           => new sfValidatorString(array('required' => false)),
      'tgl_putusan_pn'         => new sfValidatorDateTime(array('required' => false)),
      'tgl_terima_putusan'     => new sfValidatorDateTime(array('required' => false)),
      'kd_putusan_hukum'       => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'tgl_putusan_hukum'      => new sfValidatorDateTime(array('required' => false)),
      'no_barbuk'              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_barbuk'             => new sfValidatorDateTime(array('required' => false)),
      'no_konsultasi'          => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'no_p20'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_p20'                => new sfValidatorDateTime(array('required' => false)),
      'no_optimal'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_optimal'            => new sfValidatorDateTime(array('required' => false)),
      'isi_pemeriksaan'        => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'tgl_limpah_pk'          => new sfValidatorDateTime(array('required' => false)),
      'created_by'             => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'created_time'           => new sfValidatorDateTime(array('required' => false)),
      'created_ip'             => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'lastupdate_by'          => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'lastupdate_time'        => new sfValidatorDateTime(array('required' => false)),
      'lastupdate_ip'          => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'inst_satkerkd'          => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'terdakwa'               => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'jaksa_penuntut_umum'    => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'id_perkara'             => new sfValidatorInteger(array('required' => false)),
      'pasal_yg_ddkwkn'        => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'pasal_yg_dilanggar'     => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'p16_tim'                => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'dtl_dakwaan'            => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'tuntutan'               => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'amar_tuntutan'          => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'status'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'p16a_tim'               => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'ditahan_jpu_awal'       => new sfValidatorDateTime(array('required' => false)),
      'ditahan_jpu_akhir'      => new sfValidatorDateTime(array('required' => false)),
      'ditahan_jpu_tmpt'       => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'dprjng_hkm_kt_pn_awal'  => new sfValidatorDateTime(array('required' => false)),
      'dprjng_hkm_kt_pn_akhir' => new sfValidatorDateTime(array('required' => false)),
      'dprjng_hkm_kt_pn_tmpt'  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'pengalihan_tahan_awal'  => new sfValidatorDateTime(array('required' => false)),
      'pengalihan_tahan_akh'   => new sfValidatorDateTime(array('required' => false)),
      'pengalihan_tahan_tmpt'  => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'pmbtr_sjk_awal'         => new sfValidatorDateTime(array('required' => false)),
      'pmbtr_sjk_akhir'        => new sfValidatorDateTime(array('required' => false)),
      'pmbtr_dtl'              => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_putusan_hkm_tetap'  => new sfValidatorDateTime(array('required' => false)),
      'tgl_grasi'              => new sfValidatorDateTime(array('required' => false)),
      'tgl_pk'                 => new sfValidatorDateTime(array('required' => false)),
      'tgl_akta_kasasi'        => new sfValidatorDateTime(array('required' => false)),
      'tgl_akta_banding'       => new sfValidatorDateTime(array('required' => false)),
      'p16a_tgl'               => new sfValidatorDateTime(array('required' => false)),
      'p16_tgl'                => new sfValidatorDateTime(array('required' => false)),
      'idoff'                  => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'tgl_tuntut_jpu'         => new sfValidatorDateTime(array('required' => false)),
      'isi_rentut_jpu'         => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'isi_pendapat_kasi'      => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'tgl_pendapat_kasi'      => new sfValidatorDateTime(array('required' => false)),
      'nama_berkas_dakwaan'    => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'idasalperkara'          => new sfValidatorInteger(array('required' => false)),
      'idpenyelesaian'         => new sfValidatorInteger(array('required' => false)),
      'no_lanjut_pratut'       => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_lanjut_pratut'      => new sfValidatorDateTime(array('required' => false)),
      'no_henti_pratut'        => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_henti_pratut'       => new sfValidatorDateTime(array('required' => false)),
      'no_optimal_pratut'      => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'tgl_optimal_pratut'     => new sfValidatorDateTime(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('pdm_perkara[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'PDM_PERKARA';
  }

}
