<?php

/**
 * PDS_DETAIL_STR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PDS_DETAIL_STR extends BasePDS_DETAIL_STR
{
}
