<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/31 18:31:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'oracle://simkari:bandung@192.168.1.103/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.103)(PORT=1521)))(CONNECT_DATA=(SID=ORCL)))',
  'name' => 'doctrine',
)),);
