<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/26 08:44:53
sfConfig::add(array(
  'mod_reportdntpidum_enabled' => true,
  'mod_reportdntpidum_view_class' => 'sfPHP',
));
