<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/06 08:53:07
sfConfig::add(array(
  'mod_barangrampasan_enabled' => true,
  'mod_barangrampasan_view_class' => 'sfPHP',
));
