<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KP_INST_SATKER', 'doctrine');

/**
 * BaseKP_INST_SATKER
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $inst_satkerkd
 * @property string $inst_satkerinduk
 * @property string $inst_nama
 * @property string $inst_kepala
 * @property string $inst_akronim
 * @property string $inst_alamat
 * @property string $inst_telepon
 * @property string $inst_fax
 * @property string $inst_jenis
 * @property integer $inst_level
 * @property string $inst_indukpkpn
 * @property string $inst_indukbkn
 * @property string $inst_wilayahbayar
 * @property string $inst_lokinst
 * @property integer $inst_jnslokasi
 * @property integer $inst_lokkec
 * @property string $inst_lokkab
 * @property string $inst_lokprov
 * @property string $inst_kepala_nip
 * @property string $id_cabang
 * @property string $created_by
 * @property timestamp $created_time
 * @property string $created_ip
 * @property string $lastupdate_by
 * @property timestamp $lastupdate_time
 * @property string $lastupdate_ip
 * @property string $inst_intern
 * @property string $inst_satkerinduk_temp
 * @property string $inst_satkerkd_temp
 * @property boolean $is_active
 * @property string $thn_kepja
 * 
 * @method integer        getId()                    Returns the current record's "id" value
 * @method string         getInstSatkerkd()          Returns the current record's "inst_satkerkd" value
 * @method string         getInstSatkerinduk()       Returns the current record's "inst_satkerinduk" value
 * @method string         getInstNama()              Returns the current record's "inst_nama" value
 * @method string         getInstKepala()            Returns the current record's "inst_kepala" value
 * @method string         getInstAkronim()           Returns the current record's "inst_akronim" value
 * @method string         getInstAlamat()            Returns the current record's "inst_alamat" value
 * @method string         getInstTelepon()           Returns the current record's "inst_telepon" value
 * @method string         getInstFax()               Returns the current record's "inst_fax" value
 * @method string         getInstJenis()             Returns the current record's "inst_jenis" value
 * @method integer        getInstLevel()             Returns the current record's "inst_level" value
 * @method string         getInstIndukpkpn()         Returns the current record's "inst_indukpkpn" value
 * @method string         getInstIndukbkn()          Returns the current record's "inst_indukbkn" value
 * @method string         getInstWilayahbayar()      Returns the current record's "inst_wilayahbayar" value
 * @method string         getInstLokinst()           Returns the current record's "inst_lokinst" value
 * @method integer        getInstJnslokasi()         Returns the current record's "inst_jnslokasi" value
 * @method integer        getInstLokkec()            Returns the current record's "inst_lokkec" value
 * @method string         getInstLokkab()            Returns the current record's "inst_lokkab" value
 * @method string         getInstLokprov()           Returns the current record's "inst_lokprov" value
 * @method string         getInstKepalaNip()         Returns the current record's "inst_kepala_nip" value
 * @method string         getIdCabang()              Returns the current record's "id_cabang" value
 * @method string         getCreatedBy()             Returns the current record's "created_by" value
 * @method timestamp      getCreatedTime()           Returns the current record's "created_time" value
 * @method string         getCreatedIp()             Returns the current record's "created_ip" value
 * @method string         getLastupdateBy()          Returns the current record's "lastupdate_by" value
 * @method timestamp      getLastupdateTime()        Returns the current record's "lastupdate_time" value
 * @method string         getLastupdateIp()          Returns the current record's "lastupdate_ip" value
 * @method string         getInstIntern()            Returns the current record's "inst_intern" value
 * @method string         getInstSatkerindukTemp()   Returns the current record's "inst_satkerinduk_temp" value
 * @method string         getInstSatkerkdTemp()      Returns the current record's "inst_satkerkd_temp" value
 * @method boolean        getIsActive()              Returns the current record's "is_active" value
 * @method string         getThnKepja()              Returns the current record's "thn_kepja" value
 * @method KP_INST_SATKER setId()                    Sets the current record's "id" value
 * @method KP_INST_SATKER setInstSatkerkd()          Sets the current record's "inst_satkerkd" value
 * @method KP_INST_SATKER setInstSatkerinduk()       Sets the current record's "inst_satkerinduk" value
 * @method KP_INST_SATKER setInstNama()              Sets the current record's "inst_nama" value
 * @method KP_INST_SATKER setInstKepala()            Sets the current record's "inst_kepala" value
 * @method KP_INST_SATKER setInstAkronim()           Sets the current record's "inst_akronim" value
 * @method KP_INST_SATKER setInstAlamat()            Sets the current record's "inst_alamat" value
 * @method KP_INST_SATKER setInstTelepon()           Sets the current record's "inst_telepon" value
 * @method KP_INST_SATKER setInstFax()               Sets the current record's "inst_fax" value
 * @method KP_INST_SATKER setInstJenis()             Sets the current record's "inst_jenis" value
 * @method KP_INST_SATKER setInstLevel()             Sets the current record's "inst_level" value
 * @method KP_INST_SATKER setInstIndukpkpn()         Sets the current record's "inst_indukpkpn" value
 * @method KP_INST_SATKER setInstIndukbkn()          Sets the current record's "inst_indukbkn" value
 * @method KP_INST_SATKER setInstWilayahbayar()      Sets the current record's "inst_wilayahbayar" value
 * @method KP_INST_SATKER setInstLokinst()           Sets the current record's "inst_lokinst" value
 * @method KP_INST_SATKER setInstJnslokasi()         Sets the current record's "inst_jnslokasi" value
 * @method KP_INST_SATKER setInstLokkec()            Sets the current record's "inst_lokkec" value
 * @method KP_INST_SATKER setInstLokkab()            Sets the current record's "inst_lokkab" value
 * @method KP_INST_SATKER setInstLokprov()           Sets the current record's "inst_lokprov" value
 * @method KP_INST_SATKER setInstKepalaNip()         Sets the current record's "inst_kepala_nip" value
 * @method KP_INST_SATKER setIdCabang()              Sets the current record's "id_cabang" value
 * @method KP_INST_SATKER setCreatedBy()             Sets the current record's "created_by" value
 * @method KP_INST_SATKER setCreatedTime()           Sets the current record's "created_time" value
 * @method KP_INST_SATKER setCreatedIp()             Sets the current record's "created_ip" value
 * @method KP_INST_SATKER setLastupdateBy()          Sets the current record's "lastupdate_by" value
 * @method KP_INST_SATKER setLastupdateTime()        Sets the current record's "lastupdate_time" value
 * @method KP_INST_SATKER setLastupdateIp()          Sets the current record's "lastupdate_ip" value
 * @method KP_INST_SATKER setInstIntern()            Sets the current record's "inst_intern" value
 * @method KP_INST_SATKER setInstSatkerindukTemp()   Sets the current record's "inst_satkerinduk_temp" value
 * @method KP_INST_SATKER setInstSatkerkdTemp()      Sets the current record's "inst_satkerkd_temp" value
 * @method KP_INST_SATKER setIsActive()              Sets the current record's "is_active" value
 * @method KP_INST_SATKER setThnKepja()              Sets the current record's "thn_kepja" value
 * 
 * @package    dnt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKP_INST_SATKER extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('KP_INST_SATKER');
        $this->hasColumn('id', 'integer', 8, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('inst_satkerkd', 'string', 50, array(
             'notnull' => true,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('inst_satkerinduk', 'string', 12, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 12,
             ));
        $this->hasColumn('inst_nama', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('inst_kepala', 'string', 45, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 45,
             ));
        $this->hasColumn('inst_akronim', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('inst_alamat', 'string', 80, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 80,
             ));
        $this->hasColumn('inst_telepon', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_fax', 'string', 11, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 11,
             ));
        $this->hasColumn('inst_jenis', 'string', 1, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('inst_level', 'integer', 2, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('inst_indukpkpn', 'string', 25, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('inst_indukbkn', 'string', 25, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('inst_wilayahbayar', 'string', 5, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 5,
             ));
        $this->hasColumn('inst_lokinst', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('inst_jnslokasi', 'integer', 1, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('inst_lokkec', 'integer', 15, array(
             'notnull' => false,
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_lokkab', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_lokprov', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_kepala_nip', 'string', 20, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 20,
             ));
        $this->hasColumn('id_cabang', 'string', 100, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_by', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('created_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('created_ip', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('lastupdate_by', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('lastupdate_time', 'timestamp', 7, array(
             'notnull' => false,
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 7,
             ));
        $this->hasColumn('lastupdate_ip', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_intern', 'string', 15, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('inst_satkerinduk_temp', 'string', 12, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 12,
             ));
        $this->hasColumn('inst_satkerkd_temp', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('is_active', 'boolean', 1, array(
             'notnull' => false,
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('thn_kepja', 'string', 50, array(
             'notnull' => false,
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}